<?php
/**
 * Solutions Comparison block template.
 *
 * @package ACF_Module_Workbench
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$eyebrow           = trim( (string) get_field( 'eyebrow' ) );
$heading           = trim( (string) get_field( 'heading' ) );
$heading_level     = (string) get_field( 'heading_level' );
$introduction      = trim( (string) get_field( 'introduction' ) );
$solution_rows     = get_field( 'solutions' );
$criterion_rows    = get_field( 'criteria' );
$footer_note       = trim( (string) get_field( 'footer_note' ) );
$is_editor_preview = ! empty( $is_preview );
$allowed_headings  = array( 'h2', 'h3', 'h4' );
$solutions         = array();
$criteria          = array();
$recommended_found = false;

$heading_level = in_array( $heading_level, $allowed_headings, true ) ? $heading_level : 'h2';

/**
 * Normalize an optional ACF link field.
 *
 * @param mixed $link Raw ACF link value.
 * @return array{url:string,title:string,target:string}|null
 */
$normalize_link = static function ( $link ): ?array {
	if ( ! is_array( $link ) ) {
		return null;
	}

	$url    = isset( $link['url'] ) ? esc_url_raw( trim( (string) $link['url'] ) ) : '';
	$title  = isset( $link['title'] ) ? trim( (string) $link['title'] ) : '';
	$target = isset( $link['target'] ) && '_blank' === $link['target'] ? '_blank' : '';

	if ( '' === $url || '' === $title ) {
		return null;
	}

	return array(
		'url'    => $url,
		'title'  => $title,
		'target' => $target,
	);
};

if ( is_array( $solution_rows ) ) {
	foreach ( array_slice( $solution_rows, 0, 4 ) as $solution_row ) {
		if ( ! is_array( $solution_row ) ) {
			continue;
		}

		$name = isset( $solution_row['name'] ) ? trim( (string) $solution_row['name'] ) : '';

		if ( '' === $name ) {
			continue;
		}

		$is_recommended = ! $recommended_found && ! empty( $solution_row['recommended'] );
		$recommended_found = $recommended_found || $is_recommended;
		$solutions[] = array(
			'name'        => $name,
			'description' => isset( $solution_row['description'] ) ? trim( (string) $solution_row['description'] ) : '',
			'recommended' => $is_recommended,
			'badge'       => isset( $solution_row['badge'] ) ? trim( (string) $solution_row['badge'] ) : '',
			'cta'         => $normalize_link( $solution_row['cta'] ?? null ),
		);
	}
}

$allowed_value_types = array( 'included', 'optional', 'unavailable', 'custom', 'text' );

if ( is_array( $criterion_rows ) ) {
	foreach ( array_slice( $criterion_rows, 0, 12 ) as $criterion_row ) {
		if ( ! is_array( $criterion_row ) ) {
			continue;
		}

		$label = isset( $criterion_row['label'] ) ? trim( (string) $criterion_row['label'] ) : '';

		if ( '' === $label ) {
			continue;
		}

		$values = array();
		$raw_values = isset( $criterion_row['values'] ) && is_array( $criterion_row['values'] ) ? $criterion_row['values'] : array();

		foreach ( array_keys( $solutions ) as $solution_index ) {
			$raw_value = isset( $raw_values[ $solution_index ] ) && is_array( $raw_values[ $solution_index ] ) ? $raw_values[ $solution_index ] : array();
			$type      = isset( $raw_value['type'] ) ? (string) $raw_value['type'] : 'text';
			$type      = in_array( $type, $allowed_value_types, true ) ? $type : 'text';
			$detail    = isset( $raw_value['detail'] ) ? trim( (string) $raw_value['detail'] ) : '';

			$values[] = array(
				'type'   => $type,
				'detail' => $detail,
			);
		}

		$criteria[] = array(
			'label'  => $label,
			'help'   => isset( $criterion_row['help_text'] ) ? trim( (string) $criterion_row['help_text'] ) : '',
			'values' => $values,
		);
	}
}

$has_minimum_data = '' !== $heading && count( $solutions ) >= 2 && ! empty( $criteria );

if ( ! $has_minimum_data ) {
	if ( ! $is_editor_preview ) {
		return;
	}

	$wrapper_attributes = get_block_wrapper_attributes( array( 'class' => 'solutions-comparison solutions-comparison--incomplete' ) );
	?>
	<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?>>
		<p class="solutions-comparison__editor-guidance"><?php esc_html_e( 'Solutions Comparison: add a heading, at least two named solutions, and one comparison criterion to preview this block.', 'acf-module-workbench' ); ?></p>
	</div>
	<?php
	return;
}

$heading_id         = wp_unique_id( 'solutions-comparison-heading-' );
$caption_id         = wp_unique_id( 'solutions-comparison-caption-' );
$wrapper_attributes = get_block_wrapper_attributes(
	array( 'class' => 'solutions-comparison solutions-comparison--columns-' . count( $solutions ) )
);

$status_labels = array(
	'included'    => __( 'Included', 'acf-module-workbench' ),
	'optional'    => __( 'Optional', 'acf-module-workbench' ),
	'unavailable' => __( 'Not available', 'acf-module-workbench' ),
	'custom'      => __( 'Custom', 'acf-module-workbench' ),
);
$has_actions = (bool) array_filter( array_column( $solutions, 'cta' ) );
$mobile_order = array_keys( $solutions );

foreach ( $mobile_order as $position => $solution_index ) {
	if ( $solutions[ $solution_index ]['recommended'] ) {
		unset( $mobile_order[ $position ] );
		array_unshift( $mobile_order, $solution_index );
		break;
	}
}
$card_heading_level = 'h' . min( 6, (int) substr( $heading_level, 1 ) + 1 );
?>
<section <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?> aria-labelledby="<?php echo esc_attr( $heading_id ); ?>">
	<header class="solutions-comparison__header">
		<div class="solutions-comparison__heading-group">
			<?php if ( '' !== $eyebrow ) : ?>
				<p class="solutions-comparison__eyebrow"><?php echo esc_html( $eyebrow ); ?></p>
			<?php endif; ?>
			<<?php echo esc_html( $heading_level ); ?> class="solutions-comparison__heading" id="<?php echo esc_attr( $heading_id ); ?>"><?php echo esc_html( $heading ); ?></<?php echo esc_html( $heading_level ); ?>>
		</div>

		<?php if ( '' !== $introduction ) : ?>
			<p class="solutions-comparison__introduction"><?php echo esc_html( $introduction ); ?></p>
		<?php endif; ?>
	</header>

	<p class="solutions-comparison__scroll-hint" id="<?php echo esc_attr( $caption_id ); ?>"><?php esc_html_e( 'Scroll horizontally to compare every solution.', 'acf-module-workbench' ); ?></p>
	<div class="solutions-comparison__table-region" role="region" aria-labelledby="<?php echo esc_attr( $heading_id ); ?>" aria-describedby="<?php echo esc_attr( $caption_id ); ?>" tabindex="0">
		<table class="solutions-comparison__table">
			<caption class="screen-reader-text"><?php echo esc_html( sprintf( __( 'Comparison of %d solutions.', 'acf-module-workbench' ), count( $solutions ) ) ); ?></caption>
			<thead>
				<tr>
					<th class="solutions-comparison__corner" scope="col"><?php esc_html_e( 'Compare', 'acf-module-workbench' ); ?></th>
					<?php foreach ( $solutions as $solution_index => $solution ) : ?>
						<?php
						$column_classes = array( 'solutions-comparison__solution' );

						if ( $solution['recommended'] ) {
							$column_classes[] = 'solutions-comparison__solution--recommended';
						}

						if ( count( $solutions ) - 1 === $solution_index ) {
							$column_classes[] = 'solutions-comparison__cell--last-column';
						}
						?>
						<th class="<?php echo esc_attr( implode( ' ', $column_classes ) ); ?>" scope="col">
							<?php if ( $solution['recommended'] ) : ?>
								<span class="solutions-comparison__badge"><?php echo esc_html( '' !== $solution['badge'] ? $solution['badge'] : __( 'Recommended', 'acf-module-workbench' ) ); ?></span>
							<?php endif; ?>
							<span class="solutions-comparison__solution-name"><?php echo esc_html( $solution['name'] ); ?></span>
							<?php if ( '' !== $solution['description'] ) : ?>
								<span class="solutions-comparison__solution-description"><?php echo esc_html( $solution['description'] ); ?></span>
							<?php endif; ?>
						</th>
					<?php endforeach; ?>
				</tr>
			</thead>
			<tbody>
				<?php foreach ( $criteria as $criterion_index => $criterion ) : ?>
					<?php
					$is_final_body_row = ! $has_actions && count( $criteria ) - 1 === $criterion_index;
					$row_header_class  = 'solutions-comparison__criterion' . ( $is_final_body_row ? ' solutions-comparison__cell--table-end' : '' );
					?>
					<tr>
						<th class="<?php echo esc_attr( $row_header_class ); ?>" scope="row">
							<span class="solutions-comparison__criterion-label"><?php echo esc_html( $criterion['label'] ); ?></span>
							<?php if ( '' !== $criterion['help'] ) : ?>
								<span class="solutions-comparison__criterion-help"><?php echo esc_html( $criterion['help'] ); ?></span>
							<?php endif; ?>
						</th>
						<?php foreach ( $criterion['values'] as $value_index => $value ) : ?>
							<?php
							$is_recommended = ! empty( $solutions[ $value_index ]['recommended'] );
							$cell_classes = array( 'solutions-comparison__value', 'solutions-comparison__value--' . $value['type'] );

							if ( $is_recommended ) {
								$cell_classes[] = 'solutions-comparison__value--recommended';
							}

							if ( count( $criterion['values'] ) - 1 === $value_index ) {
								$cell_classes[] = 'solutions-comparison__cell--last-column';
							}

							if ( $is_final_body_row ) {
								$cell_classes[] = 'solutions-comparison__cell--table-end';
							}
							?>
							<td class="<?php echo esc_attr( implode( ' ', $cell_classes ) ); ?>">
								<?php if ( 'text' === $value['type'] ) : ?>
									<span class="solutions-comparison__value-text"><?php echo '' !== $value['detail'] ? esc_html( $value['detail'] ) : '<span aria-hidden="true">—</span><span class="screen-reader-text">' . esc_html__( 'Not specified', 'acf-module-workbench' ) . '</span>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Constructed from escaped strings. ?></span>
								<?php else : ?>
									<span class="solutions-comparison__status-mark" aria-hidden="true"><?php echo 'included' === $value['type'] ? '&#10003;' : ( 'unavailable' === $value['type'] ? '&mdash;' : '&#8226;' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Fixed presentational characters. ?></span>
									<span class="solutions-comparison__status-label"><?php echo esc_html( $status_labels[ $value['type'] ] ); ?></span>
									<?php if ( '' !== $value['detail'] ) : ?>
										<span class="solutions-comparison__value-detail"><?php echo esc_html( $value['detail'] ); ?></span>
									<?php endif; ?>
								<?php endif; ?>
							</td>
						<?php endforeach; ?>
					</tr>
				<?php endforeach; ?>
			</tbody>
			<?php if ( $has_actions ) : ?>
				<tfoot>
					<tr>
						<th class="solutions-comparison__footer-label solutions-comparison__cell--table-end" scope="row"><?php esc_html_e( 'Next step', 'acf-module-workbench' ); ?></th>
						<?php foreach ( $solutions as $solution_index => $solution ) : ?>
							<?php
							$action_cell_classes = array( 'solutions-comparison__action-cell', 'solutions-comparison__cell--table-end' );

							if ( $solution['recommended'] ) {
								$action_cell_classes[] = 'solutions-comparison__action-cell--recommended';
							}

							if ( count( $solutions ) - 1 === $solution_index ) {
								$action_cell_classes[] = 'solutions-comparison__cell--last-column';
							}
							?>
							<td class="<?php echo esc_attr( implode( ' ', $action_cell_classes ) ); ?>">
								<?php if ( null !== $solution['cta'] ) : ?>
									<a class="solutions-comparison__cta" <?php if ( $is_editor_preview ) : ?>role="link" aria-disabled="true"<?php else : ?>href="<?php echo esc_url( $solution['cta']['url'] ); ?>"<?php if ( '_blank' === $solution['cta']['target'] ) : ?> target="_blank" rel="noopener noreferrer"<?php endif; ?><?php endif; ?>>
										<span><?php echo esc_html( $solution['cta']['title'] ); ?></span><span class="solutions-comparison__cta-icon" aria-hidden="true">&rarr;</span>
									</a>
								<?php endif; ?>
							</td>
						<?php endforeach; ?>
					</tr>
				</tfoot>
			<?php endif; ?>
		</table>
	</div>

	<div class="solutions-comparison__mobile-cards">
		<?php foreach ( $mobile_order as $solution_index ) : ?>
			<?php $solution = $solutions[ $solution_index ]; ?>
			<article class="solutions-comparison__mobile-card<?php echo $solution['recommended'] ? ' solutions-comparison__mobile-card--recommended' : ''; ?>">
				<header class="solutions-comparison__mobile-card-header">
					<?php if ( $solution['recommended'] ) : ?>
						<span class="solutions-comparison__badge"><?php echo esc_html( '' !== $solution['badge'] ? $solution['badge'] : __( 'Recommended', 'acf-module-workbench' ) ); ?></span>
					<?php endif; ?>
					<<?php echo esc_html( $card_heading_level ); ?> class="solutions-comparison__mobile-card-title"><?php echo esc_html( $solution['name'] ); ?></<?php echo esc_html( $card_heading_level ); ?>>
					<?php if ( '' !== $solution['description'] ) : ?>
						<p class="solutions-comparison__mobile-card-description"><?php echo esc_html( $solution['description'] ); ?></p>
					<?php endif; ?>
				</header>
				<dl class="solutions-comparison__mobile-criteria">
					<?php foreach ( $criteria as $criterion ) : ?>
						<?php $value = $criterion['values'][ $solution_index ]; ?>
						<div class="solutions-comparison__mobile-criterion">
							<dt class="solutions-comparison__mobile-criterion-label">
								<span class="solutions-comparison__criterion-label"><?php echo esc_html( $criterion['label'] ); ?></span>
								<?php if ( '' !== $criterion['help'] ) : ?>
									<span class="solutions-comparison__criterion-help"><?php echo esc_html( $criterion['help'] ); ?></span>
								<?php endif; ?>
							</dt>
							<dd class="solutions-comparison__mobile-criterion-value solutions-comparison__value solutions-comparison__value--<?php echo esc_attr( $value['type'] ); ?>">
								<?php if ( 'text' === $value['type'] ) : ?>
									<span class="solutions-comparison__value-text"><?php echo '' !== $value['detail'] ? esc_html( $value['detail'] ) : '<span aria-hidden="true">—</span><span class="screen-reader-text">' . esc_html__( 'Not specified', 'acf-module-workbench' ) . '</span>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Constructed from escaped strings. ?></span>
								<?php else : ?>
									<span class="solutions-comparison__status-mark" aria-hidden="true"><?php echo 'included' === $value['type'] ? '&#10003;' : ( 'unavailable' === $value['type'] ? '&mdash;' : '&#8226;' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Fixed presentational characters. ?></span>
									<span class="solutions-comparison__status-label"><?php echo esc_html( $status_labels[ $value['type'] ] ); ?></span>
									<?php if ( '' !== $value['detail'] ) : ?>
										<span class="solutions-comparison__value-detail"><?php echo esc_html( $value['detail'] ); ?></span>
									<?php endif; ?>
								<?php endif; ?>
							</dd>
						</div>
					<?php endforeach; ?>
				</dl>
				<?php if ( null !== $solution['cta'] ) : ?>
					<footer class="solutions-comparison__mobile-card-footer">
						<a class="solutions-comparison__cta" <?php if ( $is_editor_preview ) : ?>role="link" aria-disabled="true"<?php else : ?>href="<?php echo esc_url( $solution['cta']['url'] ); ?>"<?php if ( '_blank' === $solution['cta']['target'] ) : ?> target="_blank" rel="noopener noreferrer"<?php endif; ?><?php endif; ?>>
							<span><?php echo esc_html( $solution['cta']['title'] ); ?></span><span class="solutions-comparison__cta-icon" aria-hidden="true">&rarr;</span>
						</a>
					</footer>
				<?php endif; ?>
			</article>
		<?php endforeach; ?>
	</div>

	<?php if ( '' !== $footer_note ) : ?>
		<p class="solutions-comparison__note"><?php echo esc_html( $footer_note ); ?></p>
	<?php endif; ?>
</section>
