<?php

/**
 * Campaign Hero block template.
 *
 * @package CR_Practice
 */

if (! defined('ABSPATH')) {
    exit;
}

$eyebrow                = trim((string) get_field('eyebrow'));
$heading_start           = trim((string) get_field('heading_start'));
$heading_emphasis        = trim((string) get_field('heading_emphasis'));
$heading_end             = trim((string) get_field('heading_end'));
$heading_level           = (string) get_field('heading_level');
$body                     = trim((string) get_field('body'));
$supporting_note          = trim((string) get_field('supporting_note'));
$secondary_label_before   = trim((string) get_field('secondary_label_before'));
$secondary_label_emphasis = trim((string) get_field('secondary_label_emphasis'));
$secondary_label_after    = trim((string) get_field('secondary_label_after'));
$desktop_image_id         = absint(get_field('desktop_image'));
$efficiency_label        = trim((string) get_field('efficiency_label'));
$efficiency_value        = trim((string) get_field('efficiency_value'));
$efficiency_description  = trim((string) get_field('efficiency_description'));
$deployment_label        = trim((string) get_field('deployment_label'));
$deployment_percentage   = get_field('deployment_percentage');
$deployment_note         = trim((string) get_field('deployment_note'));
$is_editor_preview       = ! empty($is_preview);
$allowed_heading_levels  = array('h1', 'h2', 'h3');
$asset_base_uri          = get_theme_file_uri('/parts/modules/campaign-hero/assets');

$heading_level = in_array($heading_level, $allowed_heading_levels, true) ? $heading_level : 'h2';

if (! wp_attachment_is_image($desktop_image_id)) {
    $desktop_image_id = 0;
}

$normalize_link = static function ($link): array {
    if (! is_array($link)) {
        return array();
    }

    $url    = isset($link['url']) ? trim((string) $link['url']) : '';
    $title  = isset($link['title']) ? trim((string) $link['title']) : '';
    $target = isset($link['target']) && '_blank' === $link['target'] ? '_blank' : '';

    if ('' === $url) {
        return array();
    }

    return array(
        'url'    => $url,
        'title'  => $title,
        'target' => $target,
    );
};

$primary_link   = $normalize_link(get_field('primary_link'));
$secondary_link = $normalize_link(get_field('secondary_link'));

$has_primary_link              = ! empty($primary_link) && '' !== $primary_link['title'];
$has_structured_secondary_label = '' !== $secondary_label_before || '' !== $secondary_label_emphasis || '' !== $secondary_label_after;
$has_secondary_link            = ! empty($secondary_link) && ($has_structured_secondary_label || '' !== $secondary_link['title']);

if (is_numeric($deployment_percentage)) {
    $deployment_percentage = max(0, min(100, (int) $deployment_percentage));
} else {
    $deployment_percentage = null;
}

$has_heading     = '' !== $heading_start || '' !== $heading_emphasis || '' !== $heading_end;
$has_efficiency  = '' !== $efficiency_label || '' !== $efficiency_value || '' !== $efficiency_description;
$has_deployment  = '' !== $deployment_label || null !== $deployment_percentage || '' !== $deployment_note;

if (! $has_heading) {
    if (! $is_editor_preview) {
        return;
    }

    $wrapper_attributes = get_block_wrapper_attributes(
        array(
            'class' => 'campaign-hero campaign-hero--incomplete',
        )
    );
?>
    <div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress.
            ?>>
        <p class="campaign-hero__editor-guidance"><?php esc_html_e('Campaign Hero: add heading content to preview this block.', 'cr-practice'); ?></p>
    </div>
<?php
    return;
}

$heading_id         = wp_unique_id('campaign-hero-heading-');
$wrapper_attributes = get_block_wrapper_attributes(
    array(
        'class' => 'campaign-hero',
    )
);
?>
<section <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress.
            ?> aria-labelledby="<?php echo esc_attr($heading_id); ?>">
    <img class="campaign-hero__mobile-artwork" src="<?php echo esc_url($asset_base_uri . '/mobile-artwork.svg'); ?>" alt="" aria-hidden="true">

    <div class="campaign-hero__layout">
        <div class="campaign-hero__content">
            <?php if ('' !== $eyebrow) : ?>
                <p class="campaign-hero__eyebrow">
                    <img class="campaign-hero__eyebrow-icon" src="<?php echo esc_url($asset_base_uri . '/badge-spark.svg'); ?>" alt="" aria-hidden="true">
                    <span><?php echo esc_html($eyebrow); ?></span>
                </p>
            <?php endif; ?>

            <<?php echo esc_html($heading_level); ?> class="campaign-hero__heading" id="<?php echo esc_attr($heading_id); ?>">
                <?php if ('' !== $heading_start) : ?>
                    <span><?php echo esc_html($heading_start); ?></span>
                <?php endif; ?>
                <?php if ('' !== $heading_emphasis) : ?>
                    <em><?php echo esc_html($heading_emphasis); ?></em>
                <?php endif; ?>
                <?php if ('' !== $heading_end) : ?>
                    <span><?php echo esc_html($heading_end); ?></span>
                <?php endif; ?>
            </<?php echo esc_html($heading_level); ?>>

            <?php if ('' !== $body) : ?>
                <p class="campaign-hero__body"><?php echo esc_html($body); ?></p>
            <?php endif; ?>

            <?php if ($has_primary_link || $has_secondary_link || '' !== $supporting_note) : ?>
                <div class="campaign-hero__actions">
                    <?php if ($has_primary_link || $has_secondary_link) : ?>
                        <div class="campaign-hero__buttons">
                            <?php if ($has_primary_link) : ?>
                                <a class="campaign-hero__button campaign-hero__button--primary" <?php if ($is_editor_preview) : ?> role="link" aria-disabled="true" <?php else : ?> href="<?php echo esc_url($primary_link['url']); ?>" <?php if ('_blank' === $primary_link['target']) : ?> target="_blank" rel="noopener noreferrer" <?php endif; ?><?php endif; ?>>
                                    <span><?php echo esc_html($primary_link['title']); ?></span>
                                    <img class="campaign-hero__button-icon" src="<?php echo esc_url($asset_base_uri . '/primary-cta-icon.svg'); ?>" alt="" aria-hidden="true">
                                </a>
                            <?php endif; ?>

                            <?php if ($has_secondary_link) : ?>
                                <a class="campaign-hero__button campaign-hero__button--secondary" <?php if ($is_editor_preview) : ?> role="link" aria-disabled="true" <?php else : ?> href="<?php echo esc_url($secondary_link['url']); ?>" <?php if ('_blank' === $secondary_link['target']) : ?> target="_blank" rel="noopener noreferrer" <?php endif; ?><?php endif; ?>>
                                    <?php if ($has_structured_secondary_label) : ?>
                                        <span class="campaign-hero__button-label">
                                            <?php if ('' !== $secondary_label_before) : ?><span><?php echo esc_html($secondary_label_before); ?></span><?php endif; ?>
                                            <?php if ('' !== $secondary_label_emphasis) : ?><?php if ('' !== $secondary_label_before) : ?> <?php endif; ?><strong><em><?php echo esc_html($secondary_label_emphasis); ?></em></strong><?php endif; ?>
                                            <?php if ('' !== $secondary_label_after) : ?><?php if ('' !== $secondary_label_before || '' !== $secondary_label_emphasis) : ?> <?php endif; ?><span><?php echo esc_html($secondary_label_after); ?></span><?php endif; ?>
                                        </span>
                                    <?php else : ?>
                                        <span class="campaign-hero__button-label"><?php echo esc_html($secondary_link['title']); ?></span>
                                    <?php endif; ?>
                                </a>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>

                    <?php if ('' !== $supporting_note) : ?>
                        <p class="campaign-hero__supporting-note"><span aria-hidden="true">*</span><?php echo esc_html($supporting_note); ?></p>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>

        <div class="campaign-hero__visual">
            <div class="campaign-hero__media">
                <div class="campaign-hero__media-frame">
                    <?php if ($desktop_image_id) : ?>
                        <?php
                        echo wp_get_attachment_image(
                            $desktop_image_id,
                            'large',
                            false,
                            array(
                                'class' => 'campaign-hero__media-image campaign-hero__media-image--custom',
                            )
                        ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- WordPress generates escaped image markup.
                        ?>
                    <?php else : ?>
                        <img class="campaign-hero__media-image campaign-hero__media-image--base" src="<?php echo esc_url($asset_base_uri . '/architectural-base.png'); ?>" alt="">
                        <img class="campaign-hero__media-image campaign-hero__media-image--overlay" src="<?php echo esc_url($asset_base_uri . '/architectural-overlay.png'); ?>" alt="">
                    <?php endif; ?>
                    <div class="campaign-hero__media-shade"></div>
                </div>

                <?php if ($has_efficiency) : ?>
                    <div class="campaign-hero__efficiency">
                        <?php if ('' !== $efficiency_label) : ?>
                            <div class="campaign-hero__metric-label">
                                <span class="campaign-hero__metric-icon"><img src="<?php echo esc_url($asset_base_uri . '/efficiency-icon.svg'); ?>" alt=""></span>
                                <strong><?php echo esc_html($efficiency_label); ?></strong>
                            </div>
                        <?php endif; ?>
                        <?php if ('' !== $efficiency_value) : ?>
                            <strong class="campaign-hero__efficiency-value"><?php echo esc_html($efficiency_value); ?></strong>
                        <?php endif; ?>
                        <?php if ('' !== $efficiency_description) : ?>
                            <span class="campaign-hero__efficiency-description"><?php echo esc_html($efficiency_description); ?></span>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>

                <?php if ($has_deployment) : ?>
                    <div class="campaign-hero__deployment" style="--campaign-hero-progress: <?php echo esc_attr(null !== $deployment_percentage ? $deployment_percentage : 0); ?>%;">
                        <?php if ('' !== $deployment_label || null !== $deployment_percentage) : ?>
                            <div class="campaign-hero__deployment-header">
                                <?php if ('' !== $deployment_label) : ?>
                                    <span class="campaign-hero__deployment-title"><span class="campaign-hero__status-icon"><img src="<?php echo esc_url($asset_base_uri . '/status-check.svg'); ?>" alt=""></span><?php echo esc_html($deployment_label); ?></span>
                                <?php endif; ?>
                                <?php if (null !== $deployment_percentage) : ?>
                                    <strong><?php echo esc_html($deployment_percentage); ?>%</strong>
                                <?php endif; ?>
                            </div>
                            <div class="campaign-hero__progress"><span></span></div>
                        <?php endif; ?>
                        <?php if ('' !== $deployment_note) : ?>
                            <strong class="campaign-hero__deployment-note"><?php echo esc_html($deployment_note); ?></strong>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</section>
