<?php
/**
 * Content + Media block template.
 *
 * @package ACF_Module_Workbench
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$eyebrow       = trim( (string) get_field( 'eyebrow' ) );
$heading       = trim( (string) get_field( 'heading' ) );
$body_content  = (string) get_field( 'body_content' );
$feature_rows  = get_field( 'features' );
$image_id      = absint( get_field( 'image' ) );
$media_position = get_field( 'media_position' );
$media_position = in_array( $media_position, array( 'left', 'right' ), true ) ? $media_position : 'right';
$features       = array();

if ( is_array( $feature_rows ) ) {
	foreach ( array_slice( $feature_rows, 0, 4 ) as $feature_row ) {
		$label = isset( $feature_row['label'] ) ? trim( (string) $feature_row['label'] ) : '';

		if ( '' !== $label ) {
			$features[] = $label;
		}
	}
}

$has_content = '' !== $eyebrow || '' !== $heading || '' !== trim( wp_strip_all_tags( $body_content ) ) || ! empty( $features );

if ( ! $has_content && ! $image_id ) {
	return;
}

$heading_id       = '' !== $heading ? wp_unique_id( 'content-media-heading-' ) : '';
$wrapper_classes  = sprintf( 'content-media content-media--media-%s', $media_position );
$wrapper_attributes = get_block_wrapper_attributes(
	array(
		'class' => $wrapper_classes,
	)
);
$element          = '' !== $heading ? 'section' : 'div';
$label_attribute  = '' !== $heading_id ? sprintf( ' aria-labelledby="%s"', esc_attr( $heading_id ) ) : '';
?>
<<?php echo esc_html( $element ); ?> <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?><?php echo $label_attribute; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped above. ?>>
	<div class="content-media__frame">
		<div class="content-media__layout">
			<?php if ( $image_id ) : ?>
				<div class="content-media__media">
					<?php
					echo wp_get_attachment_image(
						$image_id,
						'large',
						false,
						array(
							'class' => 'content-media__image',
						)
					); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- WordPress generates escaped image markup.
					?>
				</div>
			<?php endif; ?>

			<?php if ( $has_content ) : ?>
				<div class="content-media__content">
					<?php if ( '' !== $eyebrow ) : ?>
						<p class="content-media__eyebrow">
							<svg class="content-media__eyebrow-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
								<path d="M9.5 4A2.5 2.5 0 0 1 12 6.5v11a2.5 2.5 0 0 1-4.96.44 2.5 2.5 0 0 1-2.53-3.49 3 3 0 0 1 .34-5.58A2.5 2.5 0 0 1 9.5 4Z"></path>
								<path d="M14.5 4A2.5 2.5 0 0 0 12 6.5v11a2.5 2.5 0 0 0 4.96.44 2.5 2.5 0 0 0 2.53-3.49 3 3 0 0 0-.34-5.58A2.5 2.5 0 0 0 14.5 4Z"></path>
								<path d="M6.5 10.5H9M15 10.5h2.5M8 15h2M14 15h2"></path>
							</svg>
							<span><?php echo esc_html( $eyebrow ); ?></span>
						</p>
					<?php endif; ?>

					<?php if ( '' !== $heading ) : ?>
						<h2 class="content-media__heading" id="<?php echo esc_attr( $heading_id ); ?>"><?php echo esc_html( $heading ); ?></h2>
					<?php endif; ?>

					<?php if ( '' !== trim( wp_strip_all_tags( $body_content ) ) ) : ?>
						<div class="content-media__body">
							<?php echo wp_kses_post( $body_content ); ?>
						</div>
					<?php endif; ?>

					<?php if ( ! empty( $features ) ) : ?>
						<ul class="content-media__features" role="list">
							<?php foreach ( $features as $feature ) : ?>
								<li class="content-media__feature">
									<svg class="content-media__feature-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
										<circle class="content-media__feature-icon-circle" cx="12" cy="12" r="9"></circle>
										<path class="content-media__feature-icon-check" d="m8 12 2.5 2.5L16 9"></path>
									</svg>
									<span><?php echo esc_html( $feature ); ?></span>
								</li>
							<?php endforeach; ?>
						</ul>
					<?php endif; ?>
				</div>
			<?php endif; ?>
		</div>
	</div>
</<?php echo esc_html( $element ); ?>>
