<?php
/**
 * Impact Metrics block template.
 *
 * @package ACF_Module_Workbench
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$eyebrow           = trim( (string) get_field( 'eyebrow' ) );
$heading           = trim( (string) get_field( 'heading' ) );
$heading_level     = (string) get_field( 'heading_level' );
$introduction      = trim( (string) get_field( 'introduction' ) );
$metric_rows       = get_field( 'metrics' );
$methodology_note  = trim( (string) get_field( 'methodology_note' ) );
$cta               = get_field( 'cta' );
$is_editor_preview = ! empty( $is_preview );
$allowed_headings  = array( 'h2', 'h3', 'h4' );
$metrics           = array();

$heading_level = in_array( $heading_level, $allowed_headings, true ) ? $heading_level : 'h2';

if ( is_array( $metric_rows ) ) {
	foreach ( array_slice( $metric_rows, 0, 6 ) as $metric_row ) {
		if ( ! is_array( $metric_row ) ) {
			continue;
		}

		$value        = isset( $metric_row['value'] ) ? trim( (string) $metric_row['value'] ) : '';
		$label        = isset( $metric_row['label'] ) ? trim( (string) $metric_row['label'] ) : '';
		$context      = isset( $metric_row['context'] ) ? trim( (string) $metric_row['context'] ) : '';
		$source_label = isset( $metric_row['source_label'] ) ? trim( (string) $metric_row['source_label'] ) : '';
		$source_url   = isset( $metric_row['source_url'] ) ? esc_url_raw( trim( (string) $metric_row['source_url'] ) ) : '';

		if ( '' === $value || '' === $label ) {
			continue;
		}

		$metrics[] = array(
			'value'        => $value,
			'label'        => $label,
			'context'      => $context,
			'source_label' => $source_label,
			'source_url'   => '' !== $source_label ? $source_url : '',
		);
	}
}

/**
 * Normalize the optional ACF link field.
 *
 * @param mixed $link Raw ACF link value.
 * @return array{url:string,title:string,target:string}|null
 */
$normalize_link = static function ( $link ): ?array {
	if ( ! is_array( $link ) ) {
		return null;
	}

	$url    = isset( $link['url'] ) ? esc_url_raw( trim( (string) $link['url'] ) ) : '';
	$title  = isset( $link['title'] ) ? trim( (string) $link['title'] ) : '';
	$target = isset( $link['target'] ) && '_blank' === $link['target'] ? '_blank' : '';

	if ( '' === $url || '' === $title ) {
		return null;
	}

	return array(
		'url'    => $url,
		'title'  => $title,
		'target' => $target,
	);
};

$cta              = $normalize_link( $cta );
$has_minimum_data = '' !== $heading && count( $metrics ) >= 2;

if ( ! $has_minimum_data ) {
	if ( ! $is_editor_preview ) {
		return;
	}

	$wrapper_attributes = get_block_wrapper_attributes(
		array( 'class' => 'impact-metrics impact-metrics--incomplete' )
	);
	?>
	<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?>>
		<p class="impact-metrics__editor-guidance"><?php esc_html_e( 'Impact Metrics: add a heading and at least two complete metrics to preview this block.', 'acf-module-workbench' ); ?></p>
	</div>
	<?php
	return;
}

$heading_id         = wp_unique_id( 'impact-metrics-heading-' );
$wrapper_attributes = get_block_wrapper_attributes(
	array(
		'class' => 'impact-metrics impact-metrics--count-' . count( $metrics ),
	)
);
?>
<section <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?> aria-labelledby="<?php echo esc_attr( $heading_id ); ?>">
	<header class="impact-metrics__header">
		<div class="impact-metrics__heading-group">
			<?php if ( '' !== $eyebrow ) : ?>
				<p class="impact-metrics__eyebrow"><?php echo esc_html( $eyebrow ); ?></p>
			<?php endif; ?>

			<<?php echo esc_html( $heading_level ); ?> class="impact-metrics__heading" id="<?php echo esc_attr( $heading_id ); ?>"><?php echo esc_html( $heading ); ?></<?php echo esc_html( $heading_level ); ?>>
		</div>

		<?php if ( '' !== $introduction ) : ?>
			<p class="impact-metrics__introduction"><?php echo esc_html( $introduction ); ?></p>
		<?php endif; ?>
	</header>

	<dl class="impact-metrics__list">
		<?php foreach ( $metrics as $metric_index => $metric ) : ?>
			<?php
			$metric_count = count( $metrics );
			$position     = $metric_index + 1;
			$item_classes = array( 'impact-metrics__item' );

			if ( in_array( $metric_count, array( 3, 5 ), true ) && $metric_count === $position ) {
				$item_classes[] = 'impact-metrics__item--tablet-full';
			}

			if ( in_array( $metric_count, array( 2, 4 ), true ) || ( 5 === $metric_count && $position > $metric_count - 2 ) ) {
				$item_classes[] = 'impact-metrics__item--desktop-half';
			}
			?>
			<div class="<?php echo esc_attr( implode( ' ', $item_classes ) ); ?>">
				<dt class="impact-metrics__label"><?php echo esc_html( $metric['label'] ); ?></dt>
				<dd class="impact-metrics__value"><?php echo esc_html( $metric['value'] ); ?></dd>

				<?php if ( '' !== $metric['context'] ) : ?>
					<dd class="impact-metrics__context"><?php echo esc_html( $metric['context'] ); ?></dd>
				<?php endif; ?>

				<?php if ( '' !== $metric['source_label'] ) : ?>
					<dd class="impact-metrics__source">
						<span><?php esc_html_e( 'Source:', 'acf-module-workbench' ); ?></span>
						<cite>
							<?php if ( '' !== $metric['source_url'] && ! $is_editor_preview ) : ?>
								<a href="<?php echo esc_url( $metric['source_url'] ); ?>"><?php echo esc_html( $metric['source_label'] ); ?></a>
							<?php else : ?>
								<?php echo esc_html( $metric['source_label'] ); ?>
							<?php endif; ?>
						</cite>
					</dd>
				<?php endif; ?>
			</div>
		<?php endforeach; ?>
	</dl>

	<?php if ( '' !== $methodology_note || null !== $cta ) : ?>
		<footer class="impact-metrics__footer<?php echo '' !== $methodology_note && null !== $cta ? '' : ' impact-metrics__footer--single'; ?>">
			<?php if ( '' !== $methodology_note ) : ?>
				<p class="impact-metrics__methodology"><span class="impact-metrics__methodology-label"><?php esc_html_e( 'Methodology:', 'acf-module-workbench' ); ?></span> <?php echo esc_html( $methodology_note ); ?></p>
			<?php endif; ?>

			<?php if ( null !== $cta ) : ?>
				<a class="impact-metrics__cta"<?php if ( $is_editor_preview ) : ?> role="link" aria-disabled="true"<?php else : ?> href="<?php echo esc_url( $cta['url'] ); ?>"<?php if ( '_blank' === $cta['target'] ) : ?> target="_blank" rel="noopener noreferrer"<?php endif; ?><?php endif; ?>>
					<span class="impact-metrics__cta-label"><?php echo esc_html( $cta['title'] ); ?></span>
					<span class="impact-metrics__cta-icon" aria-hidden="true">&rarr;</span>
				</a>
			<?php endif; ?>
		</footer>
	<?php endif; ?>
</section>
