<?php
/**
 * Sticky Feature Showcase block template.
 *
 * @package ACF_Module_Workbench
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$eyebrow           = trim( (string) get_field( 'eyebrow' ) );
$heading           = trim( (string) get_field( 'heading' ) );
$heading_level     = (string) get_field( 'heading_level' );
$introduction      = trim( (string) get_field( 'introduction' ) );
$step_rows         = get_field( 'steps' );
$allowed_headings  = array( 'h2', 'h3', 'h4' );
$steps             = array();
$is_editor_preview = ! empty( $is_preview );

$heading_level      = in_array( $heading_level, $allowed_headings, true ) ? $heading_level : 'h2';
$step_heading_level = 'h' . min( 6, (int) substr( $heading_level, 1 ) + 1 );

if ( is_array( $step_rows ) ) {
	foreach ( $step_rows as $step_row ) {
		$label       = isset( $step_row['label'] ) ? trim( (string) $step_row['label'] ) : '';
		$title       = isset( $step_row['title'] ) ? trim( (string) $step_row['title'] ) : '';
		$summary     = isset( $step_row['summary'] ) ? trim( (string) $step_row['summary'] ) : '';
		$image_id    = isset( $step_row['image'] ) ? absint( $step_row['image'] ) : 0;
		$link        = isset( $step_row['link'] ) && is_array( $step_row['link'] ) ? $step_row['link'] : array();
		$link_url    = isset( $link['url'] ) ? trim( (string) $link['url'] ) : '';
		$link_title  = isset( $link['title'] ) ? trim( (string) $link['title'] ) : '';
		$link_target = isset( $link['target'] ) && '_blank' === $link['target'] ? '_blank' : '_self';

		if ( '' === $title || '' === $summary || ! $image_id || ! wp_attachment_is_image( $image_id ) ) {
			continue;
		}

		$steps[] = array(
			'label'       => $label,
			'title'       => $title,
			'summary'     => $summary,
			'image_id'    => $image_id,
			'link_url'    => $link_url,
			'link_title'  => $link_title,
			'link_target' => $link_target,
		);
	}
}

if ( '' === $heading || count( $steps ) < 2 ) {
	if ( ! $is_editor_preview ) {
		return;
	}

	$wrapper_attributes = get_block_wrapper_attributes(
		array( 'class' => 'sticky-feature-showcase sticky-feature-showcase--incomplete' )
	);
	?>
	<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?>>
		<p class="sticky-feature-showcase__editor-guidance"><?php esc_html_e( 'Sticky Feature Showcase: add a heading and at least two complete steps to preview this block.', 'acf-module-workbench' ); ?></p>
	</div>
	<?php
	return;
}

$instance_id        = wp_unique_id( 'sticky-feature-showcase-' );
$heading_id         = $instance_id . '-heading';
$wrapper_attributes = get_block_wrapper_attributes(
	array( 'class' => 'sticky-feature-showcase' )
);
?>
<section <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?> aria-labelledby="<?php echo esc_attr( $heading_id ); ?>" data-sticky-feature-showcase<?php if ( $is_editor_preview ) : ?> data-editor-preview="true"<?php endif; ?>>
	<header class="sticky-feature-showcase__header">
		<?php if ( '' !== $eyebrow ) : ?>
			<p class="sticky-feature-showcase__eyebrow"><?php echo esc_html( $eyebrow ); ?></p>
		<?php endif; ?>
		<<?php echo esc_html( $heading_level ); ?> class="sticky-feature-showcase__heading" id="<?php echo esc_attr( $heading_id ); ?>"><?php echo esc_html( $heading ); ?></<?php echo esc_html( $heading_level ); ?>>
		<?php if ( '' !== $introduction ) : ?>
			<p class="sticky-feature-showcase__introduction"><?php echo esc_html( $introduction ); ?></p>
		<?php endif; ?>
	</header>

	<div class="sticky-feature-showcase__layout">
		<div class="sticky-feature-showcase__visual-column" aria-hidden="true"></div>
		<div class="sticky-feature-showcase__steps">
			<?php foreach ( $steps as $index => $step ) : ?>
				<article class="sticky-feature-showcase__step" data-showcase-step data-step-index="<?php echo esc_attr( (string) $index ); ?>">
					<figure class="sticky-feature-showcase__inline-media">
						<?php
						echo wp_get_attachment_image(
							$step['image_id'],
							'large',
							false,
							array(
								'class'   => 'sticky-feature-showcase__image',
								'loading' => 0 === $index ? 'eager' : 'lazy',
								'sizes'   => '(min-width: 900px) 52vw, calc(100vw - 2rem)',
							)
						); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- WordPress generates escaped image markup.
						?>
					</figure>
					<div class="sticky-feature-showcase__step-copy">
						<p class="sticky-feature-showcase__step-kicker">
							<span class="sticky-feature-showcase__step-number"><?php echo esc_html( str_pad( (string) ( $index + 1 ), 2, '0', STR_PAD_LEFT ) ); ?></span>
							<?php if ( '' !== $step['label'] ) : ?><span><?php echo esc_html( $step['label'] ); ?></span><?php endif; ?>
						</p>
						<<?php echo esc_html( $step_heading_level ); ?> class="sticky-feature-showcase__step-title"><?php echo esc_html( $step['title'] ); ?></<?php echo esc_html( $step_heading_level ); ?>>
						<p class="sticky-feature-showcase__summary"><?php echo esc_html( $step['summary'] ); ?></p>
						<?php if ( '' !== $step['link_url'] && '' !== $step['link_title'] ) : ?>
							<a class="sticky-feature-showcase__link" href="<?php echo esc_url( $step['link_url'] ); ?>" target="<?php echo esc_attr( $step['link_target'] ); ?>"<?php if ( '_blank' === $step['link_target'] ) : ?> rel="noopener noreferrer"<?php endif; ?>>
								<span><?php echo esc_html( $step['link_title'] ); ?></span>
								<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M5 12h14M13 6l6 6-6 6"></path></svg>
							</a>
						<?php endif; ?>
					</div>
				</article>
			<?php endforeach; ?>
		</div>
	</div>
</section>
