<?php
/**
 * Before / After Comparison block template.
 *
 * @package ACF_Module_Workbench
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$eyebrow           = trim( (string) get_field( 'eyebrow' ) );
$heading           = trim( (string) get_field( 'heading' ) );
$heading_level     = (string) get_field( 'heading_level' );
$introduction      = trim( (string) get_field( 'introduction' ) );
$before_image_id   = absint( get_field( 'before_image' ) );
$before_label      = trim( (string) get_field( 'before_label' ) );
$after_image_id    = absint( get_field( 'after_image' ) );
$after_label       = trim( (string) get_field( 'after_label' ) );
$caption           = trim( (string) get_field( 'caption' ) );
$aspect_ratio      = (string) get_field( 'aspect_ratio' );
$initial_position  = absint( get_field( 'initial_position' ) );
$is_editor_preview = ! empty( $is_preview );
$allowed_headings  = array( 'h2', 'h3', 'h4' );
$allowed_ratios    = array( 'wide', 'landscape', 'square' );

$heading_level    = in_array( $heading_level, $allowed_headings, true ) ? $heading_level : 'h2';
$aspect_ratio     = in_array( $aspect_ratio, $allowed_ratios, true ) ? $aspect_ratio : 'wide';
$initial_position = min( 90, max( 10, $initial_position ?: 50 ) );
$before_label     = '' !== $before_label ? $before_label : __( 'Before', 'acf-module-workbench' );
$after_label      = '' !== $after_label ? $after_label : __( 'After', 'acf-module-workbench' );
$has_before_image = $before_image_id && wp_attachment_is_image( $before_image_id );
$has_after_image  = $after_image_id && wp_attachment_is_image( $after_image_id );
$is_complete      = $has_before_image && $has_after_image;

if ( ! $is_complete ) {
	if ( ! $is_editor_preview ) {
		return;
	}

	$missing = array();

	if ( ! $has_before_image ) {
		$missing[] = __( 'a before image', 'acf-module-workbench' );
	}

	if ( ! $has_after_image ) {
		$missing[] = __( 'an after image', 'acf-module-workbench' );
	}

	$wrapper_attributes = get_block_wrapper_attributes(
		array( 'class' => 'before-after-comparison before-after-comparison--incomplete' )
	);
	?>
	<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?>>
		<p class="before-after-comparison__editor-guidance">
			<?php
			echo esc_html(
				sprintf(
					/* translators: %s: Required fields missing from the block. */
					__( 'Before / After Comparison: add %s to preview this block.', 'acf-module-workbench' ),
					implode( __( ' and ', 'acf-module-workbench' ), $missing )
				)
			);
			?>
		</p>
	</div>
	<?php
	return;
}

$instance_id       = wp_unique_id( 'before-after-comparison-' );
$heading_id        = $instance_id . '-heading';
$range_id          = $instance_id . '-range';
$output_id         = $instance_id . '-output';
$root_tag          = '' !== $heading ? 'section' : 'div';
$wrapper_attributes = get_block_wrapper_attributes(
	array(
		'class' => 'before-after-comparison before-after-comparison--ratio-' . $aspect_ratio . ( $is_editor_preview ? ' is-enhanced' : '' ),
	)
);
$comparison_label = sprintf(
	/* translators: 1: Before label. 2: After label. */
	__( 'Image comparison: %1$s and %2$s', 'acf-module-workbench' ),
	$before_label,
	$after_label
);
?>
<<?php echo esc_html( $root_tag ); ?> <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?><?php if ( '' !== $heading ) : ?> aria-labelledby="<?php echo esc_attr( $heading_id ); ?>"<?php endif; ?> data-before-after-comparison<?php if ( $is_editor_preview ) : ?> data-editor-preview="true"<?php endif; ?>>
	<?php if ( '' !== $eyebrow || '' !== $heading || '' !== $introduction ) : ?>
		<header class="before-after-comparison__header">
			<?php if ( '' !== $eyebrow ) : ?>
				<p class="before-after-comparison__eyebrow"><?php echo esc_html( $eyebrow ); ?></p>
			<?php endif; ?>

			<?php if ( '' !== $heading ) : ?>
				<<?php echo esc_html( $heading_level ); ?> class="before-after-comparison__heading" id="<?php echo esc_attr( $heading_id ); ?>"><?php echo esc_html( $heading ); ?></<?php echo esc_html( $heading_level ); ?>>
			<?php endif; ?>

			<?php if ( '' !== $introduction ) : ?>
				<p class="before-after-comparison__introduction"><?php echo esc_html( $introduction ); ?></p>
			<?php endif; ?>
		</header>
	<?php endif; ?>

	<figure class="before-after-comparison__figure" aria-label="<?php echo esc_attr( $comparison_label ); ?>">
		<div class="before-after-comparison__stage" style="--before-after-position: <?php echo esc_attr( (string) $initial_position ); ?>%;">
			<div class="before-after-comparison__media before-after-comparison__media--before">
				<?php
				echo wp_get_attachment_image(
					$before_image_id,
					'large',
					false,
					array(
						'class' => 'before-after-comparison__image',
						'sizes' => '(min-width: 1200px) 1120px, calc(100vw - 2rem)',
					)
				); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- WordPress generates escaped image markup.
				?>
				<span class="before-after-comparison__image-label"><?php echo esc_html( $before_label ); ?></span>
			</div>

			<div class="before-after-comparison__media before-after-comparison__media--after">
				<?php
				echo wp_get_attachment_image(
					$after_image_id,
					'large',
					false,
					array(
						'class' => 'before-after-comparison__image',
						'sizes' => '(min-width: 1200px) 1120px, calc(100vw - 2rem)',
					)
				); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- WordPress generates escaped image markup.
				?>
				<span class="before-after-comparison__image-label"><?php echo esc_html( $after_label ); ?></span>
			</div>

			<div class="before-after-comparison__divider" aria-hidden="true">
				<span class="before-after-comparison__handle">&#8596;</span>
			</div>

			<label class="before-after-comparison__screen-reader-text" for="<?php echo esc_attr( $range_id ); ?>">
				<?php echo esc_html( sprintf( /* translators: %s: After-image label. */ __( 'Reveal %s image', 'acf-module-workbench' ), $after_label ) ); ?>
			</label>
			<input class="before-after-comparison__range" id="<?php echo esc_attr( $range_id ); ?>" type="range" min="0" max="100" step="1" value="<?php echo esc_attr( (string) $initial_position ); ?>" aria-describedby="<?php echo esc_attr( $output_id ); ?>"<?php if ( ! $is_editor_preview ) : ?> hidden<?php endif; ?>>
		</div>

		<div class="before-after-comparison__controls"<?php if ( ! $is_editor_preview ) : ?> hidden<?php endif; ?>>
			<span><?php esc_html_e( 'Drag the handle or use the arrow keys to compare.', 'acf-module-workbench' ); ?></span>
			<output id="<?php echo esc_attr( $output_id ); ?>" for="<?php echo esc_attr( $range_id ); ?>"><?php echo esc_html( sprintf( /* translators: 1: Percentage revealed. 2: After-image label. */ __( '%1$d%% %2$s', 'acf-module-workbench' ), $initial_position, $after_label ) ); ?></output>
		</div>

		<?php if ( '' !== $caption ) : ?>
			<figcaption class="before-after-comparison__caption"><?php echo esc_html( $caption ); ?></figcaption>
		<?php endif; ?>
	</figure>
</<?php echo esc_html( $root_tag ); ?>>
