<?php
/**
 * Accordion block template.
 *
 * @package CR_Practice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$title            = trim( (string) get_field( 'title' ) );
$subtitle         = trim( (string) get_field( 'subtitle' ) );
$heading_level    = (string) get_field( 'heading_level' );
$item_rows        = get_field( 'items' );
$allowed_headings = array( 'h2', 'h3', 'h4' );
$items            = array();

$heading_level = in_array( $heading_level, $allowed_headings, true ) ? $heading_level : 'h2';

if ( is_array( $item_rows ) ) {
	foreach ( $item_rows as $item_row ) {
		$question = isset( $item_row['question'] ) ? trim( (string) $item_row['question'] ) : '';
		$answer   = isset( $item_row['answer'] ) ? (string) $item_row['answer'] : '';

		if ( '' === $question || '' === trim( wp_strip_all_tags( $answer ) ) ) {
			continue;
		}

		$open_value = isset( $item_row['open_by_default'] ) ? strtolower( (string) $item_row['open_by_default'] ) : '';

		$items[] = array(
			'question' => $question,
			'answer'   => $answer,
			'open'     => in_array( $open_value, array( '1', 'true', 'yes', 'on' ), true ),
		);
	}
}

if ( '' === $title || empty( $items ) ) {
	return;
}

$heading_id         = wp_unique_id( 'accordion-heading-' );
$wrapper_attributes = get_block_wrapper_attributes(
	array(
		'class' => 'accordion',
	)
);
?>
<section <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?> aria-labelledby="<?php echo esc_attr( $heading_id ); ?>">
	<header class="accordion__header">
		<<?php echo esc_html( $heading_level ); ?> class="accordion__title" id="<?php echo esc_attr( $heading_id ); ?>"><?php echo esc_html( $title ); ?></<?php echo esc_html( $heading_level ); ?>>

		<?php if ( '' !== $subtitle ) : ?>
			<p class="accordion__subtitle"><?php echo esc_html( $subtitle ); ?></p>
		<?php endif; ?>
	</header>

	<div class="accordion__items">
		<?php foreach ( $items as $item ) : ?>
			<details class="accordion__item"<?php if ( $item['open'] ) : ?> open<?php endif; ?>>
				<summary class="accordion__summary">
					<span class="accordion__question"><?php echo esc_html( $item['question'] ); ?></span>
					<svg class="accordion__chevron" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
						<path d="m6 9 6 6 6-6"></path>
					</svg>
				</summary>
				<div class="accordion__answer-region">
					<div class="accordion__answer-inner">
						<div class="accordion__answer">
							<?php echo wp_kses_post( $item['answer'] ); ?>
						</div>
					</div>
				</div>
			</details>
		<?php endforeach; ?>
	</div>
</section>
