<?php
/**
 * Filtered Content Grid block template.
 *
 * @package CR_Practice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$title             = trim( (string) get_field( 'title' ) );
$introduction      = trim( (string) get_field( 'introduction' ) );
$heading_level     = (string) get_field( 'heading_level' );
$selected_terms    = get_field( 'categories' );
$posts_per_page    = absint( get_field( 'posts_per_page' ) );
$is_editor_preview = ! empty( $is_preview );
$allowed_headings  = array( 'h2', 'h3', 'h4' );
$card_headings     = array(
	'h2' => 'h3',
	'h3' => 'h4',
	'h4' => 'h5',
);
$category_ids      = array();
$posts             = array();
$filter_terms      = array();

$heading_level  = in_array( $heading_level, $allowed_headings, true ) ? $heading_level : 'h2';
$card_heading   = $card_headings[ $heading_level ];
$posts_per_page = max( 1, min( 24, $posts_per_page ? $posts_per_page : 9 ) );

if ( '' === $title && ! $is_editor_preview ) {
	return;
}

if ( is_array( $selected_terms ) ) {
	foreach ( $selected_terms as $selected_term ) {
		$term_id = $selected_term instanceof WP_Term ? (int) $selected_term->term_id : absint( $selected_term );
		$term    = $term_id ? get_term( $term_id, 'category' ) : null;

		if ( ! $term instanceof WP_Term || isset( $category_ids[ $term_id ] ) ) {
			continue;
		}

		$category_ids[ $term_id ] = $term_id;
	}
}

$query_args = array(
	'post_type'           => 'post',
	'post_status'         => 'publish',
	'posts_per_page'      => $posts_per_page,
	'orderby'             => 'date',
	'order'               => 'DESC',
	'ignore_sticky_posts' => true,
	'no_found_rows'       => true,
);

if ( ! empty( $category_ids ) ) {
	$query_args['category__in'] = array_values( $category_ids );
}

$content_query = new WP_Query( $query_args );

foreach ( $content_query->posts as $post_object ) {
	if ( ! $post_object instanceof WP_Post ) {
		continue;
	}

	$permalink  = get_permalink( $post_object );
	$post_title = trim( get_the_title( $post_object ) );

	if ( ! is_string( $permalink ) || '' === $permalink || '' === $post_title ) {
		continue;
	}

	$terms                = get_the_terms( $post_object, 'category' );
	$post_categories      = array();
	$post_filter_term_ids = array();

	if ( is_array( $terms ) ) {
		foreach ( $terms as $term ) {
			if ( ! $term instanceof WP_Term || '' === trim( $term->name ) ) {
				continue;
			}

			$term_id           = (int) $term->term_id;
			$post_categories[] = $term;

			if ( ! empty( $category_ids ) && ! isset( $category_ids[ $term_id ] ) ) {
				continue;
			}

			$post_filter_term_ids[] = $term_id;

			if ( ! isset( $filter_terms[ $term_id ] ) ) {
				$filter_terms[ $term_id ] = array(
					'term'  => $term,
					'count' => 0,
				);
			}

			++$filter_terms[ $term_id ]['count'];
		}
	}

	$image_id = get_post_thumbnail_id( $post_object );
	$image_id = $image_id && wp_attachment_is_image( $image_id ) ? $image_id : 0;

	$posts[] = array(
		'title'           => $post_title,
		'permalink'       => $permalink,
		'excerpt'         => trim( (string) $post_object->post_excerpt ),
		'image_id'        => $image_id,
		'categories'      => $post_categories,
		'filter_term_ids' => array_values( array_unique( $post_filter_term_ids ) ),
		'date_display'    => (string) get_the_date( '', $post_object ),
		'date_machine'    => (string) get_the_date( DATE_W3C, $post_object ),
	);
}

if ( empty( $posts ) && ! $is_editor_preview ) {
	return;
}

uasort(
	$filter_terms,
	static function ( array $first, array $second ): int {
		return strcasecmp( $first['term']->name, $second['term']->name );
	}
);

$instance_id        = wp_unique_id( 'filtered-content-grid-' );
$heading_id         = $instance_id . '-heading';
$status_id          = $instance_id . '-status';
$display_title      = '' !== $title ? $title : __( 'Filtered Content Grid', 'cr-practice' );
$is_incomplete      = '' === $title;
$has_filters        = count( $filter_terms ) > 1;
$post_count         = count( $posts );
$initial_status     = $post_count
	? sprintf(
		/* translators: %d: Number of articles shown. */
		_n( 'Showing all %d article.', 'Showing all %d articles.', $post_count, 'cr-practice' ),
		$post_count
	)
	: __( 'No published posts match this grid yet.', 'cr-practice' );
$wrapper_attributes = get_block_wrapper_attributes(
	array(
		'class' => sprintf(
			'filtered-content-grid filtered-content-grid--count-%d%s',
			$post_count,
			$is_incomplete ? ' filtered-content-grid--incomplete' : ''
		),
	)
);
?>
<section <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?> aria-labelledby="<?php echo esc_attr( $heading_id ); ?>" data-filtered-content-grid data-transition-scope="<?php echo esc_attr( $instance_id ); ?>">
	<?php if ( $is_incomplete ) : ?>
		<p class="filtered-content-grid__editor-notice"><?php esc_html_e( 'Block preview: add a section title in Block settings before publishing.', 'cr-practice' ); ?></p>
	<?php endif; ?>

	<header class="filtered-content-grid__header">
		<<?php echo esc_html( $heading_level ); ?> class="filtered-content-grid__title" id="<?php echo esc_attr( $heading_id ); ?>"><?php echo esc_html( $display_title ); ?></<?php echo esc_html( $heading_level ); ?>>

		<?php if ( '' !== $introduction ) : ?>
			<p class="filtered-content-grid__introduction"><?php echo esc_html( $introduction ); ?></p>
		<?php endif; ?>
	</header>

	<?php if ( $has_filters ) : ?>
		<div
			class="filtered-content-grid__filters"
			role="group"
			aria-label="<?php esc_attr_e( 'Filter articles by category', 'cr-practice' ); ?>"
			aria-describedby="<?php echo esc_attr( $status_id ); ?>"
			hidden
		>
			<button class="filtered-content-grid__filter" type="button" data-filter="all" aria-pressed="true">
				<span><?php esc_html_e( 'All', 'cr-practice' ); ?></span>
				<span class="filtered-content-grid__filter-count" aria-hidden="true"><?php echo esc_html( (string) $post_count ); ?></span>
			</button>

			<?php foreach ( $filter_terms as $term_id => $filter_term ) : ?>
				<button class="filtered-content-grid__filter" type="button" data-filter="<?php echo esc_attr( (string) $term_id ); ?>" aria-pressed="false">
					<span><?php echo esc_html( $filter_term['term']->name ); ?></span>
					<span class="filtered-content-grid__filter-count" aria-hidden="true"><?php echo esc_html( (string) $filter_term['count'] ); ?></span>
				</button>
			<?php endforeach; ?>
		</div>
	<?php endif; ?>

	<p
		class="filtered-content-grid__status<?php echo $has_filters ? '' : ' filtered-content-grid__status--visually-hidden'; ?>"
		id="<?php echo esc_attr( $status_id ); ?>"
		aria-live="polite"
		data-status-singular="<?php esc_attr_e( 'Showing 1 article.', 'cr-practice' ); ?>"
		data-status-plural="<?php esc_attr_e( 'Showing %d articles.', 'cr-practice' ); ?>"
	><?php echo esc_html( $initial_status ); ?></p>

	<?php if ( ! empty( $posts ) ) : ?>
	<ul class="filtered-content-grid__items" role="list" aria-busy="false">
		<?php foreach ( $posts as $post_item ) : ?>
			<?php
			$card_heading_id = wp_unique_id( 'filtered-content-grid-card-heading-' );
			$card_classes    = 'filtered-content-grid__card';

			if ( ! $post_item['image_id'] ) {
				$card_classes .= ' filtered-content-grid__card--without-image';
			}

			if ( '' === $post_item['excerpt'] ) {
				$card_classes .= ' filtered-content-grid__card--without-excerpt';
			}
			?>
			<li class="filtered-content-grid__item" data-categories="<?php echo esc_attr( implode( ',', $post_item['filter_term_ids'] ) ); ?>">
				<article class="<?php echo esc_attr( $card_classes ); ?>" aria-labelledby="<?php echo esc_attr( $card_heading_id ); ?>">
					<div class="filtered-content-grid__media">
						<?php if ( $post_item['image_id'] ) : ?>
							<?php
							echo wp_get_attachment_image(
								$post_item['image_id'],
								'large',
								false,
								array(
									'class' => 'filtered-content-grid__image',
								)
							); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- WordPress generates escaped image markup.
							?>
						<?php else : ?>
							<div class="filtered-content-grid__placeholder" aria-hidden="true">
								<svg class="filtered-content-grid__placeholder-icon" viewBox="0 0 64 48" focusable="false">
									<rect x="5" y="5" width="54" height="38" rx="3"></rect>
									<circle cx="46" cy="16" r="5"></circle>
									<path d="M10 37 24 23l9 9 7-7 14 12"></path>
								</svg>
							</div>
						<?php endif; ?>
					</div>

					<div class="filtered-content-grid__content">
						<?php if ( ! empty( $post_item['categories'] ) ) : ?>
							<ul class="filtered-content-grid__categories" role="list">
								<?php foreach ( $post_item['categories'] as $category ) : ?>
									<li class="filtered-content-grid__category"><?php echo esc_html( $category->name ); ?></li>
								<?php endforeach; ?>
							</ul>
						<?php endif; ?>

						<<?php echo esc_html( $card_heading ); ?> class="filtered-content-grid__card-title" id="<?php echo esc_attr( $card_heading_id ); ?>">
							<a class="filtered-content-grid__link"<?php if ( $is_editor_preview ) : ?> role="link" aria-disabled="true"<?php else : ?> href="<?php echo esc_url( $post_item['permalink'] ); ?>"<?php endif; ?>><?php echo esc_html( $post_item['title'] ); ?></a>
						</<?php echo esc_html( $card_heading ); ?>>

						<?php if ( '' !== $post_item['excerpt'] ) : ?>
							<p class="filtered-content-grid__excerpt"><?php echo esc_html( $post_item['excerpt'] ); ?></p>
						<?php endif; ?>

						<?php if ( '' !== $post_item['date_display'] && '' !== $post_item['date_machine'] ) : ?>
							<time class="filtered-content-grid__date" datetime="<?php echo esc_attr( $post_item['date_machine'] ); ?>"><?php echo esc_html( $post_item['date_display'] ); ?></time>
						<?php endif; ?>
					</div>
				</article>
			</li>
		<?php endforeach; ?>
	</ul>
	<?php else : ?>
		<div class="filtered-content-grid__empty-state">
			<p><?php esc_html_e( 'No published posts match this grid yet.', 'cr-practice' ); ?></p>
		</div>
	<?php endif; ?>
</section>
