<?php
/**
 * Tabbed Content block template.
 *
 * @package CR_Practice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$title            = trim( (string) get_field( 'title' ) );
$introduction     = trim( (string) get_field( 'introduction' ) );
$heading_level    = (string) get_field( 'heading_level' );
$background_id    = absint( get_field( 'background_image' ) );
$tab_rows         = get_field( 'tabs' );
$allowed_headings = array( 'h2', 'h3', 'h4' );
$tabs             = array();

$heading_level       = in_array( $heading_level, $allowed_headings, true ) ? $heading_level : 'h2';
$panel_heading_level = 'h' . ( (int) substr( $heading_level, 1 ) + 1 );

if ( is_array( $tab_rows ) ) {
	foreach ( $tab_rows as $tab_row ) {
		$label         = isset( $tab_row['label'] ) ? trim( (string) $tab_row['label'] ) : '';
		$panel_heading = isset( $tab_row['panel_heading'] ) ? trim( (string) $tab_row['panel_heading'] ) : '';
		$content       = isset( $tab_row['content'] ) ? (string) $tab_row['content'] : '';
		$cta           = isset( $tab_row['cta'] ) && is_array( $tab_row['cta'] ) ? $tab_row['cta'] : array();

		if ( '' === $label || '' === trim( wp_strip_all_tags( $content ) ) ) {
			continue;
		}

		$tabs[] = array(
			'label'         => $label,
			'panel_heading' => $panel_heading,
			'content'       => $content,
			'cta_url'       => isset( $cta['url'] ) ? trim( (string) $cta['url'] ) : '',
			'cta_title'     => isset( $cta['title'] ) ? trim( (string) $cta['title'] ) : '',
			'cta_target'    => isset( $cta['target'] ) && '_blank' === $cta['target'] ? '_blank' : '_self',
		);
	}
}

if ( '' === $title || count( $tabs ) < 2 ) {
	return;
}

$instance_id        = wp_unique_id( 'tabbed-content-' );
$heading_id         = $instance_id . '-heading';
$wrapper_attributes = get_block_wrapper_attributes(
	array(
		'class' => 'tabbed-content',
	)
);
?>
<section <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?> aria-labelledby="<?php echo esc_attr( $heading_id ); ?>" data-tabbed-content>
	<?php if ( $background_id ) : ?>
		<div class="tabbed-content__background" aria-hidden="true">
			<?php
			echo wp_get_attachment_image(
				$background_id,
				'full',
				false,
				array(
					'class' => 'tabbed-content__background-image',
					'alt'   => '',
				)
			); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- WordPress generates escaped image markup.
			?>
		</div>
	<?php endif; ?>

	<div class="tabbed-content__inner">
		<header class="tabbed-content__header">
			<<?php echo esc_html( $heading_level ); ?> class="tabbed-content__title" id="<?php echo esc_attr( $heading_id ); ?>"><?php echo esc_html( $title ); ?></<?php echo esc_html( $heading_level ); ?>>

			<?php if ( '' !== $introduction ) : ?>
				<p class="tabbed-content__introduction"><?php echo esc_html( $introduction ); ?></p>
			<?php endif; ?>
		</header>

		<div class="tabbed-content__widget">
			<div class="tabbed-content__tablist" role="tablist" aria-labelledby="<?php echo esc_attr( $heading_id ); ?>" hidden>
				<?php foreach ( $tabs as $index => $tab ) : ?>
					<?php
					$tab_id   = $instance_id . '-tab-' . ( $index + 1 );
					$panel_id = $instance_id . '-panel-' . ( $index + 1 );
					?>
					<button
						class="tabbed-content__tab"
						type="button"
						role="tab"
						id="<?php echo esc_attr( $tab_id ); ?>"
						aria-controls="<?php echo esc_attr( $panel_id ); ?>"
						aria-selected="<?php echo 0 === $index ? 'true' : 'false'; ?>"
						tabindex="<?php echo 0 === $index ? '0' : '-1'; ?>"
					><?php echo esc_html( $tab['label'] ); ?></button>
				<?php endforeach; ?>
			</div>

			<div class="tabbed-content__panels">
				<?php foreach ( $tabs as $index => $tab ) : ?>
					<?php
					$tab_id   = $instance_id . '-tab-' . ( $index + 1 );
					$panel_id = $instance_id . '-panel-' . ( $index + 1 );
					?>
					<section
						class="tabbed-content__panel"
						id="<?php echo esc_attr( $panel_id ); ?>"
						role="tabpanel"
						aria-labelledby="<?php echo esc_attr( $tab_id ); ?>"
					>
						<p class="tabbed-content__fallback-label"><?php echo esc_html( $tab['label'] ); ?></p>

						<div class="tabbed-content__panel-layout">
							<div class="tabbed-content__panel-copy">
								<?php if ( '' !== $tab['panel_heading'] ) : ?>
									<<?php echo esc_html( $panel_heading_level ); ?> class="tabbed-content__panel-heading"><?php echo esc_html( $tab['panel_heading'] ); ?></<?php echo esc_html( $panel_heading_level ); ?>>
								<?php endif; ?>

								<div class="tabbed-content__content">
									<?php echo wp_kses_post( $tab['content'] ); ?>
								</div>

								<?php if ( '' !== $tab['cta_url'] && '' !== $tab['cta_title'] ) : ?>
									<a class="tabbed-content__cta" href="<?php echo esc_url( $tab['cta_url'] ); ?>" target="<?php echo esc_attr( $tab['cta_target'] ); ?>"<?php if ( '_blank' === $tab['cta_target'] ) : ?> rel="noopener noreferrer"<?php endif; ?>>
										<span><?php echo esc_html( $tab['cta_title'] ); ?></span>
										<svg class="tabbed-content__cta-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
											<path d="M5 12h14M13 6l6 6-6 6"></path>
										</svg>
									</a>
								<?php endif; ?>
							</div>

							<div class="tabbed-content__stage" aria-hidden="true">
								<span class="tabbed-content__stage-label">Stage</span>
								<span class="tabbed-content__stage-number"><?php echo esc_html( str_pad( (string) ( $index + 1 ), 2, '0', STR_PAD_LEFT ) ); ?></span>
							</div>
						</div>
					</section>
				<?php endforeach; ?>
			</div>
		</div>
	</div>
</section>
