<?php
/**
 * CTA Banner block template.
 *
 * @package ACF_Module_Workbench
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$heading_before    = trim( (string) get_field( 'heading_before' ) );
$heading_emphasis  = trim( (string) get_field( 'heading_emphasis' ) );
$heading_after     = trim( (string) get_field( 'heading_after' ) );
$heading_level     = (string) get_field( 'heading_level' );
$primary_link      = get_field( 'primary_link' );
$secondary_link    = get_field( 'secondary_link' );
$reassurance_note  = trim( (string) get_field( 'reassurance_note' ) );
$testimonial_quote = trim( (string) get_field( 'testimonial_quote' ) );
$testimonial_name  = trim( (string) get_field( 'testimonial_name' ) );
$testimonial_role  = trim( (string) get_field( 'testimonial_role' ) );
$is_editor_preview = ! empty( $is_preview );
$allowed_headings  = array( 'h2', 'h3', 'h4' );

$heading_level = in_array( $heading_level, $allowed_headings, true ) ? $heading_level : 'h2';

/**
 * Normalize one ACF link field.
 *
 * @param mixed $link Raw ACF link value.
 * @return array{url:string,title:string,target:string}|null
 */
$normalize_link = static function ( $link ): ?array {
	if ( ! is_array( $link ) ) {
		return null;
	}

	$url    = isset( $link['url'] ) ? trim( (string) $link['url'] ) : '';
	$title  = isset( $link['title'] ) ? trim( (string) $link['title'] ) : '';
	$target = isset( $link['target'] ) && '_blank' === $link['target'] ? '_blank' : '';

	if ( '' === $url || '' === $title ) {
		return null;
	}

	return array(
		'url'    => $url,
		'title'  => $title,
		'target' => $target,
	);
};

$primary_link    = $normalize_link( $primary_link );
$secondary_link  = $normalize_link( $secondary_link );
$has_heading     = '' !== $heading_before || '' !== $heading_emphasis || '' !== $heading_after;
$has_testimonial = '' !== $testimonial_quote && '' !== $testimonial_name;

if ( ! $has_heading || null === $primary_link ) {
	if ( ! $is_editor_preview ) {
		return;
	}

	$wrapper_attributes = get_block_wrapper_attributes(
		array( 'class' => 'cta-banner cta-banner--incomplete' )
	);
	?>
	<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?>>
		<p class="cta-banner__editor-guidance"><?php esc_html_e( 'CTA Banner: add heading content and a complete primary link to preview this block.', 'acf-module-workbench' ); ?></p>
	</div>
	<?php
	return;
}

$heading_id         = wp_unique_id( 'cta-banner-heading-' );
$asset_base_uri     = get_theme_file_uri( '/parts/modules/cta-banner/assets' );
$wrapper_attributes = get_block_wrapper_attributes(
	array( 'class' => 'cta-banner' )
);
?>
<section <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?> aria-labelledby="<?php echo esc_attr( $heading_id ); ?>">
	<span class="cta-banner__glow cta-banner__glow--primary" aria-hidden="true"></span>
	<span class="cta-banner__glow cta-banner__glow--stack" aria-hidden="true"></span>
	<img class="cta-banner__background-lines" src="<?php echo esc_url( $asset_base_uri . '/background-lines.svg' ); ?>" alt="" aria-hidden="true">

	<div class="cta-banner__inner">
		<div class="cta-banner__main">
			<<?php echo esc_html( $heading_level ); ?> class="cta-banner__heading" id="<?php echo esc_attr( $heading_id ); ?>">
				<?php if ( '' !== $heading_before ) : ?><span><?php echo esc_html( $heading_before ); ?></span><?php endif; ?><?php if ( '' !== $heading_emphasis ) : ?><?php if ( '' !== $heading_before ) : ?> <?php endif; ?><em><?php echo esc_html( $heading_emphasis ); ?></em><?php endif; ?><?php if ( '' !== $heading_after ) : ?><?php if ( '' !== $heading_before || '' !== $heading_emphasis ) : ?> <?php endif; ?><span><?php echo esc_html( $heading_after ); ?></span><?php endif; ?>
			</<?php echo esc_html( $heading_level ); ?>>

			<div class="cta-banner__action-group">
				<div class="cta-banner__actions">
					<a class="cta-banner__button cta-banner__button--primary"<?php if ( $is_editor_preview ) : ?> role="link" aria-disabled="true"<?php else : ?> href="<?php echo esc_url( $primary_link['url'] ); ?>"<?php if ( '_blank' === $primary_link['target'] ) : ?> target="_blank" rel="noopener noreferrer"<?php endif; ?><?php endif; ?>><?php echo esc_html( $primary_link['title'] ); ?></a>

					<?php if ( null !== $secondary_link ) : ?>
						<a class="cta-banner__button cta-banner__button--secondary"<?php if ( $is_editor_preview ) : ?> role="link" aria-disabled="true"<?php else : ?> href="<?php echo esc_url( $secondary_link['url'] ); ?>"<?php if ( '_blank' === $secondary_link['target'] ) : ?> target="_blank" rel="noopener noreferrer"<?php endif; ?><?php endif; ?>>
							<span><?php echo esc_html( $secondary_link['title'] ); ?></span>
							<span class="cta-banner__button-icon" aria-hidden="true"></span>
						</a>
					<?php endif; ?>
				</div>

				<?php if ( '' !== $reassurance_note ) : ?>
					<p class="cta-banner__reassurance"><span aria-hidden="true">*</span><?php echo esc_html( $reassurance_note ); ?></p>
				<?php endif; ?>
			</div>
		</div>

		<?php if ( $has_testimonial ) : ?>
			<figure class="cta-banner__testimonial">
				<blockquote class="cta-banner__quote">
					<p><?php echo esc_html( $testimonial_quote ); ?></p>
				</blockquote>

				<figcaption class="cta-banner__attribution">
					<strong><?php echo esc_html( $testimonial_name ); ?></strong>
					<?php if ( '' !== $testimonial_role ) : ?>
						<span><?php echo esc_html( $testimonial_role ); ?></span>
					<?php endif; ?>
				</figcaption>
			</figure>
		<?php endif; ?>
	</div>
</section>
