<?php
/**
 * Inline Media block template.
 *
 * @package ACF_Module_Workbench
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$eyebrow               = trim( (string) get_field( 'eyebrow' ) );
$heading               = trim( (string) get_field( 'heading' ) );
$heading_level         = (string) get_field( 'heading_level' );
$body                  = trim( (string) get_field( 'body' ) );
$media_position        = (string) get_field( 'media_position' );
$video_id              = absint( get_field( 'video' ) );
$poster_id             = absint( get_field( 'poster' ) );
$captions_id           = absint( get_field( 'captions' ) );
$captions_language     = strtolower( trim( (string) get_field( 'captions_language' ) ) );
$captions_label        = trim( (string) get_field( 'captions_label' ) );
$transcript            = (string) get_field( 'transcript' );
$is_editor_preview     = ! empty( $is_preview );
$allowed_headings      = array( 'h2', 'h3', 'h4' );
$allowed_positions     = array( 'left', 'right' );
$allowed_video_mimes   = array( 'video/mp4', 'video/webm', 'video/ogg', 'video/quicktime', 'video/x-m4v' );
$heading_level         = in_array( $heading_level, $allowed_headings, true ) ? $heading_level : 'h2';
$media_position        = in_array( $media_position, $allowed_positions, true ) ? $media_position : 'right';
$video_mime            = $video_id ? (string) get_post_mime_type( $video_id ) : '';
$video_url             = $video_id ? wp_get_attachment_url( $video_id ) : false;
$has_video             = is_string( $video_url ) && '' !== $video_url && in_array( $video_mime, $allowed_video_mimes, true );
$has_poster            = $poster_id && wp_attachment_is_image( $poster_id );
$captions_mime         = $captions_id ? (string) get_post_mime_type( $captions_id ) : '';
$captions_url          = $captions_id ? wp_get_attachment_url( $captions_id ) : false;
$has_valid_language    = 1 === preg_match( '/^[a-z]{2,3}(?:-[a-z0-9]{2,8})*$/', $captions_language );
$has_captions          = 'text/vtt' === $captions_mime && is_string( $captions_url ) && '' !== $captions_url && $has_valid_language && '' !== $captions_label;
$has_transcript        = '' !== trim( wp_strip_all_tags( $transcript ) );
$is_complete           = '' !== $heading && $has_video;

if ( ! $is_complete ) {
	if ( ! $is_editor_preview ) {
		return;
	}

	$missing_fields = array();

	if ( '' === $heading ) {
		$missing_fields[] = __( 'a heading', 'acf-module-workbench' );
	}

	if ( ! $has_video ) {
		$missing_fields[] = __( 'a supported video', 'acf-module-workbench' );
	}

	$wrapper_attributes = get_block_wrapper_attributes(
		array(
			'class' => 'inline-media inline-media--incomplete',
		)
	);
	?>
	<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?>>
		<p class="inline-media__editor-guidance">
			<?php
			echo esc_html(
				sprintf(
					/* translators: %s: Comma-separated list of missing required fields. */
					__( 'Inline Media: add %s to preview this block.', 'acf-module-workbench' ),
					implode( __( ' and ', 'acf-module-workbench' ), $missing_fields )
				)
			);
			?>
		</p>
	</div>
	<?php
	return;
}

$metadata             = wp_get_attachment_metadata( $video_id );
$duration             = is_array( $metadata ) && isset( $metadata['length_formatted'] ) ? trim( (string) $metadata['length_formatted'] ) : '';
$instance_id          = wp_unique_id( 'inline-media-' );
$heading_id           = $instance_id . '-heading';
$transcript_id        = $instance_id . '-transcript';
$poster_url           = $has_poster ? wp_get_attachment_image_url( $poster_id, 'large' ) : false;
$wrapper_attributes   = get_block_wrapper_attributes(
	array(
		'class' => sprintf(
			'inline-media inline-media--media-%1$s%2$s',
			$media_position,
			$has_poster ? ' inline-media--has-poster' : ' inline-media--without-poster'
		),
	)
);
?>
<section <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?> aria-labelledby="<?php echo esc_attr( $heading_id ); ?>" data-inline-media<?php if ( $is_editor_preview ) : ?> data-editor-preview="true"<?php endif; ?>>
	<div class="inline-media__layout">
		<div class="inline-media__content">
			<?php if ( '' !== $eyebrow ) : ?>
				<p class="inline-media__eyebrow"><?php echo esc_html( $eyebrow ); ?></p>
			<?php endif; ?>

			<<?php echo esc_html( $heading_level ); ?> class="inline-media__heading" id="<?php echo esc_attr( $heading_id ); ?>"><?php echo esc_html( $heading ); ?></<?php echo esc_html( $heading_level ); ?>>

			<?php if ( '' !== $body ) : ?>
				<p class="inline-media__body"><?php echo esc_html( $body ); ?></p>
			<?php endif; ?>

			<?php if ( '' !== $duration ) : ?>
				<p class="inline-media__duration">
					<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><circle cx="12" cy="12" r="9"></circle><path d="M12 7v5l3 2"></path></svg>
					<span><?php echo esc_html( $duration ); ?></span>
				</p>
			<?php endif; ?>
		</div>

		<?php if ( $is_editor_preview ) : ?>
			<div class="inline-media__player inline-media__player--preview">
				<?php if ( $has_poster ) : ?>
					<?php
					echo wp_get_attachment_image(
						$poster_id,
						'large',
						false,
						array(
							'class' => 'inline-media__preview-image',
						)
					); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- WordPress generates escaped image markup.
					?>
				<?php else : ?>
					<div class="inline-media__preview-placeholder" aria-hidden="true"></div>
				<?php endif; ?>
				<span class="inline-media__play inline-media__play--preview" aria-hidden="true">
					<svg viewBox="0 0 24 24" focusable="false"><path d="m9 7 8 5-8 5Z"></path></svg>
				</span>
			</div>
		<?php else : ?>
			<div class="inline-media__player">
				<video class="inline-media__video" controls playsinline preload="none" aria-label="<?php echo esc_attr( sprintf( /* translators: %s: Video section heading. */ __( 'Video: %s', 'acf-module-workbench' ), $heading ) ); ?>"<?php if ( is_string( $poster_url ) && '' !== $poster_url ) : ?> poster="<?php echo esc_url( $poster_url ); ?>"<?php endif; ?>>
					<source src="<?php echo esc_url( $video_url ); ?>" type="<?php echo esc_attr( $video_mime ); ?>">
					<?php if ( $has_captions ) : ?>
						<track kind="captions" src="<?php echo esc_url( $captions_url ); ?>" srclang="<?php echo esc_attr( $captions_language ); ?>" label="<?php echo esc_attr( $captions_label ); ?>" default>
					<?php endif; ?>
					<a href="<?php echo esc_url( $video_url ); ?>"><?php esc_html_e( 'Open the video file', 'acf-module-workbench' ); ?></a>
				</video>

				<?php if ( $has_poster ) : ?>
					<div class="inline-media__poster-transition" hidden data-inline-media-poster aria-hidden="true">
						<?php
						echo wp_get_attachment_image(
							$poster_id,
							'large',
							false,
							array(
								'alt'   => '',
								'class' => 'inline-media__poster-transition-image',
							)
						); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- WordPress generates escaped image markup.
						?>
					</div>
					<button class="inline-media__play" type="button" hidden data-inline-media-play>
						<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="m9 7 8 5-8 5Z"></path></svg>
						<span class="inline-media__play-label"><?php esc_html_e( 'Play video', 'acf-module-workbench' ); ?></span>
					</button>
				<?php endif; ?>
			</div>
		<?php endif; ?>

		<?php if ( $has_transcript ) : ?>
			<div class="inline-media__transcript" data-inline-media-transcript>
				<button class="inline-media__transcript-toggle" type="button" aria-expanded="false" aria-controls="<?php echo esc_attr( $transcript_id ); ?>" hidden data-inline-media-transcript-toggle>
					<?php esc_html_e( 'View transcript', 'acf-module-workbench' ); ?>
				</button>
				<div class="inline-media__transcript-content" id="<?php echo esc_attr( $transcript_id ); ?>">
					<div class="inline-media__transcript-content-inner">
						<?php echo wp_kses_post( $transcript ); ?>
					</div>
				</div>
			</div>
		<?php endif; ?>
	</div>
</section>
