<?php
/**
 * Meet the Team block template.
 *
 * @package ACF_Module_Workbench
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$eyebrow           = trim( (string) get_field( 'eyebrow' ) );
$heading           = trim( (string) get_field( 'heading' ) );
$introduction      = trim( (string) get_field( 'introduction' ) );
$heading_level     = (string) get_field( 'heading_level' );
$careers_link      = get_field( 'careers_link' );
$show_filter       = (bool) get_field( 'show_department_filter' );
$filter_label      = trim( (string) get_field( 'filter_label' ) );
$all_label         = trim( (string) get_field( 'all_label' ) );
$member_rows       = get_field( 'team_members' );
$members           = array();
$departments       = array();
$is_editor_preview = ! empty( $is_preview );
$allowed_headings  = array( 'h2', 'h3', 'h4' );
$member_headings   = array( 'h2' => 'h3', 'h3' => 'h4', 'h4' => 'h5' );

$heading_level  = in_array( $heading_level, $allowed_headings, true ) ? $heading_level : 'h2';
$member_heading = $member_headings[ $heading_level ];
$filter_label   = '' !== $filter_label ? $filter_label : __( 'Departments', 'acf-module-workbench' );
$all_label      = '' !== $all_label ? $all_label : __( 'All', 'acf-module-workbench' );

if ( is_array( $member_rows ) ) {
	foreach ( array_slice( $member_rows, 0, 16 ) as $member_row ) {
		$name       = isset( $member_row['name'] ) ? trim( (string) $member_row['name'] ) : '';
		$role       = isset( $member_row['role'] ) ? trim( (string) $member_row['role'] ) : '';
		$department = isset( $member_row['department'] ) ? trim( (string) $member_row['department'] ) : '';
		$bio        = isset( $member_row['bio'] ) ? trim( (string) $member_row['bio'] ) : '';
		$image_id   = isset( $member_row['portrait'] ) ? absint( $member_row['portrait'] ) : 0;
		$link       = isset( $member_row['profile_link'] ) && is_array( $member_row['profile_link'] ) ? $member_row['profile_link'] : array();

		if ( '' === $name ) {
			continue;
		}

		$image_id        = $image_id && wp_attachment_is_image( $image_id ) ? $image_id : 0;
		$department_slug = '' !== $department ? sanitize_title( $department ) : '';
		$link_url        = isset( $link['url'] ) ? trim( (string) $link['url'] ) : '';
		$link_title      = isset( $link['title'] ) ? trim( (string) $link['title'] ) : '';
		$link_target     = isset( $link['target'] ) && '_blank' === $link['target'] ? '_blank' : '';

		if ( '' !== $department_slug && ! isset( $departments[ $department_slug ] ) ) {
			$departments[ $department_slug ] = $department;
		}

		$members[] = array(
			'name'            => $name,
			'role'            => $role,
			'bio'             => $bio,
			'department'      => $department,
			'department_slug' => $department_slug,
			'image_id'        => $image_id,
			'link_url'        => $link_url,
			'link_title'      => $link_title,
			'link_target'     => $link_target,
		);
	}
}

if ( '' === $heading || empty( $members ) ) {
	if ( ! $is_editor_preview ) {
		return;
	}

	$wrapper_attributes = get_block_wrapper_attributes(
		array( 'class' => 'meet-the-team meet-the-team--incomplete' )
	);
	?>
	<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?>>
		<p class="meet-the-team__editor-guidance"><?php esc_html_e( 'Meet the Team: add a heading and at least one named team member to preview this block.', 'acf-module-workbench' ); ?></p>
	</div>
	<?php
	return;
}

natcasesort( $departments );

$careers_url    = is_array( $careers_link ) && isset( $careers_link['url'] ) ? trim( (string) $careers_link['url'] ) : '';
$careers_title  = is_array( $careers_link ) && isset( $careers_link['title'] ) ? trim( (string) $careers_link['title'] ) : '';
$careers_target = is_array( $careers_link ) && isset( $careers_link['target'] ) && '_blank' === $careers_link['target'] ? '_blank' : '';
$has_filter     = $show_filter && count( $departments ) > 1;
$instance_id    = wp_unique_id( 'meet-the-team-' );
$heading_id     = $instance_id . '-heading';
$filter_id      = $instance_id . '-department';
$status_id      = $instance_id . '-status';
$member_count   = count( $members );
$initial_status = sprintf(
	/* translators: %d: Number of team members shown. */
	_n( 'Showing %d team member.', 'Showing %d team members.', $member_count, 'acf-module-workbench' ),
	$member_count
);
$wrapper_attributes = get_block_wrapper_attributes(
	array(
		'class' => sprintf( 'meet-the-team meet-the-team--count-%d', $member_count ),
	)
);
$icon_path = get_theme_file_path( '/parts/modules/meet-the-team/assets/briefcase.svg' );
$icon_uri  = get_theme_file_uri( '/parts/modules/meet-the-team/assets/briefcase.svg' );
?>
<section <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?> aria-labelledby="<?php echo esc_attr( $heading_id ); ?>" data-meet-the-team>
	<header class="meet-the-team__header">
		<div class="meet-the-team__introduction-group">
			<?php if ( '' !== $eyebrow ) : ?>
				<p class="meet-the-team__eyebrow"><?php echo esc_html( $eyebrow ); ?></p>
			<?php endif; ?>

			<<?php echo esc_html( $heading_level ); ?> class="meet-the-team__heading" id="<?php echo esc_attr( $heading_id ); ?>"><?php echo esc_html( $heading ); ?></<?php echo esc_html( $heading_level ); ?>>

			<?php if ( '' !== $introduction ) : ?>
				<p class="meet-the-team__introduction"><?php echo esc_html( $introduction ); ?></p>
			<?php endif; ?>
		</div>

		<?php if ( '' !== $careers_url && '' !== $careers_title ) : ?>
			<a class="meet-the-team__careers-link"<?php if ( $is_editor_preview ) : ?> role="link" aria-disabled="true"<?php else : ?> href="<?php echo esc_url( $careers_url ); ?>"<?php endif; ?><?php if ( '' !== $careers_target && ! $is_editor_preview ) : ?> target="_blank" rel="noopener noreferrer"<?php endif; ?>>
				<span><?php echo esc_html( $careers_title ); ?></span>
				<?php if ( file_exists( $icon_path ) ) : ?>
					<img class="meet-the-team__careers-icon" src="<?php echo esc_url( $icon_uri ); ?>" width="20" height="20" alt="">
				<?php endif; ?>
			</a>
		<?php endif; ?>
	</header>

	<?php if ( $has_filter ) : ?>
		<div class="meet-the-team__filter" hidden data-team-filter>
			<label class="meet-the-team__filter-label" for="<?php echo esc_attr( $filter_id ); ?>"><?php echo esc_html( $filter_label ); ?></label>
			<div class="meet-the-team__select-wrap">
				<select class="meet-the-team__select" id="<?php echo esc_attr( $filter_id ); ?>" aria-describedby="<?php echo esc_attr( $status_id ); ?>" data-team-filter-select>
					<option value="all"><?php echo esc_html( $all_label ); ?></option>
					<?php foreach ( $departments as $department_slug => $department_name ) : ?>
						<option value="<?php echo esc_attr( $department_slug ); ?>"><?php echo esc_html( $department_name ); ?></option>
					<?php endforeach; ?>
				</select>
			</div>
		</div>
	<?php endif; ?>

	<p
		class="meet-the-team__status"
		id="<?php echo esc_attr( $status_id ); ?>"
		aria-live="polite"
		data-status-singular="<?php esc_attr_e( 'Showing 1 team member.', 'acf-module-workbench' ); ?>"
		data-status-plural="<?php esc_attr_e( 'Showing %d team members.', 'acf-module-workbench' ); ?>"
	><?php echo esc_html( $initial_status ); ?></p>

	<ul class="meet-the-team__grid" role="list">
		<?php foreach ( $members as $member ) : ?>
			<?php
			$card_heading_id = wp_unique_id( 'meet-the-team-member-' );
			$bio_panel_id    = $card_heading_id . '-bio';
			$card_classes    = 'meet-the-team__card';

			if ( ! $member['image_id'] ) {
				$card_classes .= ' meet-the-team__card--without-image';
			}
			?>
			<li class="meet-the-team__item" data-department="<?php echo esc_attr( $member['department_slug'] ); ?>">
				<article class="<?php echo esc_attr( $card_classes ); ?>" aria-labelledby="<?php echo esc_attr( $card_heading_id ); ?>">
					<?php if ( $member['image_id'] ) : ?>
						<div class="meet-the-team__media">
							<?php if ( '' !== $member['bio'] ) : ?>
								<button class="meet-the-team__media-trigger" type="button" aria-controls="<?php echo esc_attr( $bio_panel_id ); ?>" aria-expanded="false" aria-label="<?php echo esc_attr( sprintf( /* translators: %s: Team member name. */ __( 'Read biography for %s', 'acf-module-workbench' ), $member['name'] ) ); ?>" data-team-bio-trigger disabled>
							<?php endif; ?>
							<?php
							echo wp_get_attachment_image(
								$member['image_id'],
								'large',
								false,
								array(
									'class'   => 'meet-the-team__portrait',
									'loading' => 'lazy',
								)
							); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- WordPress generates escaped image markup.
							?>
							<?php if ( '' !== $member['bio'] ) : ?>
								</button>
							<?php endif; ?>
						</div>
					<?php endif; ?>

					<div class="meet-the-team__member-content">
						<<?php echo esc_html( $member_heading ); ?> class="meet-the-team__name" id="<?php echo esc_attr( $card_heading_id ); ?>">
							<?php if ( '' !== $member['bio'] ) : ?>
								<button class="meet-the-team__bio-trigger" type="button" aria-controls="<?php echo esc_attr( $bio_panel_id ); ?>" aria-expanded="false" data-team-bio-trigger disabled><?php echo esc_html( $member['name'] ); ?></button>
							<?php elseif ( '' !== $member['link_url'] ) : ?>
								<a class="meet-the-team__profile-link"<?php if ( $is_editor_preview ) : ?> role="link" aria-disabled="true"<?php else : ?> href="<?php echo esc_url( $member['link_url'] ); ?>"<?php endif; ?><?php if ( '' !== $member['link_target'] && ! $is_editor_preview ) : ?> target="_blank" rel="noopener noreferrer"<?php endif; ?>><?php echo esc_html( $member['name'] ); ?></a>
							<?php else : ?>
								<?php echo esc_html( $member['name'] ); ?>
							<?php endif; ?>
						</<?php echo esc_html( $member_heading ); ?>>

						<?php if ( '' !== $member['role'] ) : ?>
							<p class="meet-the-team__role"><?php echo esc_html( $member['role'] ); ?></p>
						<?php endif; ?>

						<?php if ( '' !== $member['bio'] ) : ?>
							<div class="meet-the-team__bio-panel" id="<?php echo esc_attr( $bio_panel_id ); ?>" aria-labelledby="<?php echo esc_attr( $card_heading_id ); ?>" data-team-bio-panel>
								<div class="meet-the-team__bio-panel-header">
									<p class="meet-the-team__bio-panel-name" aria-hidden="true"><?php echo esc_html( $member['name'] ); ?></p>
									<button class="meet-the-team__bio-close" type="button" data-team-bio-close hidden aria-label="<?php echo esc_attr( sprintf( /* translators: %s: Team member name. */ __( 'Close biography for %s', 'acf-module-workbench' ), $member['name'] ) ); ?>">
										<span aria-hidden="true"></span>
									</button>
								</div>
								<p class="meet-the-team__bio"><?php echo esc_html( $member['bio'] ); ?></p>

								<?php if ( '' !== $member['link_url'] ) : ?>
									<a class="meet-the-team__bio-profile-link"<?php if ( $is_editor_preview ) : ?> role="link" aria-disabled="true"<?php else : ?> href="<?php echo esc_url( $member['link_url'] ); ?>"<?php endif; ?><?php if ( '' !== $member['link_target'] && ! $is_editor_preview ) : ?> target="_blank" rel="noopener noreferrer"<?php endif; ?>><?php echo esc_html( '' !== $member['link_title'] ? $member['link_title'] : sprintf( /* translators: %s: Team member name. */ __( 'View %s’s profile', 'acf-module-workbench' ), $member['name'] ) ); ?></a>
								<?php endif; ?>
							</div>
						<?php endif; ?>
					</div>
				</article>
			</li>
		<?php endforeach; ?>
	</ul>
</section>
