<?php
/**
 * Case Study Spotlight block template.
 *
 * @package ACF_Module_Workbench
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$eyebrow           = trim( (string) get_field( 'eyebrow' ) );
$heading           = trim( (string) get_field( 'heading' ) );
$heading_level     = (string) get_field( 'heading_level' );
$introduction      = trim( (string) get_field( 'introduction' ) );
$client_name       = trim( (string) get_field( 'client_name' ) );
$industry          = trim( (string) get_field( 'industry' ) );
$logo_id           = absint( get_field( 'client_logo' ) );
$image_id          = absint( get_field( 'image' ) );
$challenge         = (string) get_field( 'challenge' );
$approach          = (string) get_field( 'approach' );
$outcome_rows      = get_field( 'outcomes' );
$testimonial_quote = trim( (string) get_field( 'testimonial_quote' ) );
$testimonial_name  = trim( (string) get_field( 'testimonial_name' ) );
$testimonial_role  = trim( (string) get_field( 'testimonial_role' ) );
$case_study_link   = get_field( 'case_study_link' );
$is_editor_preview = ! empty( $is_preview );
$allowed_headings  = array( 'h2', 'h3', 'h4' );
$child_headings    = array( 'h2' => 'h3', 'h3' => 'h4', 'h4' => 'h5' );
$outcomes          = array();

$heading_level       = in_array( $heading_level, $allowed_headings, true ) ? $heading_level : 'h2';
$child_heading_level = $child_headings[ $heading_level ];
$logo_id             = $logo_id && wp_attachment_is_image( $logo_id ) ? $logo_id : 0;
$image_id            = $image_id && wp_attachment_is_image( $image_id ) ? $image_id : 0;
$has_challenge       = '' !== trim( wp_strip_all_tags( $challenge ) );
$has_approach        = '' !== trim( wp_strip_all_tags( $approach ) );

if ( is_array( $outcome_rows ) ) {
	foreach ( array_slice( $outcome_rows, 0, 4 ) as $outcome_row ) {
		if ( ! is_array( $outcome_row ) ) {
			continue;
		}

		$value  = isset( $outcome_row['value'] ) ? trim( (string) $outcome_row['value'] ) : '';
		$label  = isset( $outcome_row['label'] ) ? trim( (string) $outcome_row['label'] ) : '';
		$detail = isset( $outcome_row['detail'] ) ? trim( (string) $outcome_row['detail'] ) : '';

		if ( '' === $value || '' === $label ) {
			continue;
		}

		$outcomes[] = array(
			'value'  => $value,
			'label'  => $label,
			'detail' => $detail,
		);
	}
}

/**
 * Normalize the optional ACF link field.
 *
 * @param mixed $link Raw ACF link value.
 * @return array{url:string,title:string,target:string}|null
 */
$normalize_link = static function ( $link ): ?array {
	if ( ! is_array( $link ) ) {
		return null;
	}

	$url    = isset( $link['url'] ) ? trim( (string) $link['url'] ) : '';
	$title  = isset( $link['title'] ) ? trim( (string) $link['title'] ) : '';
	$target = isset( $link['target'] ) && '_blank' === $link['target'] ? '_blank' : '';

	if ( '' === $url || '' === $title ) {
		return null;
	}

	return array(
		'url'    => $url,
		'title'  => $title,
		'target' => $target,
	);
};

$case_study_link    = $normalize_link( $case_study_link );
$has_testimonial    = '' !== $testimonial_quote && '' !== $testimonial_name;
$has_complete_story = '' !== $heading && '' !== $client_name && $has_challenge && $has_approach && count( $outcomes ) >= 2;

if ( ! $has_complete_story ) {
	if ( ! $is_editor_preview ) {
		return;
	}

	$wrapper_attributes = get_block_wrapper_attributes(
		array( 'class' => 'case-study-spotlight case-study-spotlight--incomplete' )
	);
	?>
	<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?>>
		<p class="case-study-spotlight__editor-guidance"><?php esc_html_e( 'Case Study Spotlight: add a heading, client, challenge, approach, and at least two complete outcomes to preview this block.', 'acf-module-workbench' ); ?></p>
	</div>
	<?php
	return;
}

$heading_id         = wp_unique_id( 'case-study-spotlight-heading-' );
$wrapper_attributes = get_block_wrapper_attributes(
	array( 'class' => 'case-study-spotlight' )
);
?>
<section <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?> aria-labelledby="<?php echo esc_attr( $heading_id ); ?>">
	<header class="case-study-spotlight__header">
		<div class="case-study-spotlight__heading-group">
			<?php if ( '' !== $eyebrow ) : ?>
				<p class="case-study-spotlight__eyebrow"><?php echo esc_html( $eyebrow ); ?></p>
			<?php endif; ?>

			<<?php echo esc_html( $heading_level ); ?> class="case-study-spotlight__heading" id="<?php echo esc_attr( $heading_id ); ?>"><?php echo esc_html( $heading ); ?></<?php echo esc_html( $heading_level ); ?>>

			<?php if ( '' !== $introduction ) : ?>
				<p class="case-study-spotlight__introduction"><?php echo esc_html( $introduction ); ?></p>
			<?php endif; ?>
		</div>

		<div class="case-study-spotlight__client">
			<?php if ( $logo_id ) : ?>
				<div class="case-study-spotlight__logo">
					<?php
					echo wp_get_attachment_image(
						$logo_id,
						'medium',
						false,
						array( 'class' => 'case-study-spotlight__logo-image' )
					); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- WordPress generates escaped image markup.
					?>
				</div>
			<?php endif; ?>

			<div class="case-study-spotlight__client-copy">
				<span class="case-study-spotlight__client-label"><?php esc_html_e( 'Client', 'acf-module-workbench' ); ?></span>
				<strong class="case-study-spotlight__client-name"><?php echo esc_html( $client_name ); ?></strong>
				<?php if ( '' !== $industry ) : ?>
					<span class="case-study-spotlight__industry"><?php echo esc_html( $industry ); ?></span>
				<?php endif; ?>
			</div>
		</div>
	</header>

	<div class="case-study-spotlight__story<?php echo $image_id ? '' : ' case-study-spotlight__story--without-media'; ?>">
		<?php if ( $image_id ) : ?>
			<div class="case-study-spotlight__media">
				<?php
				echo wp_get_attachment_image(
					$image_id,
					'large',
					false,
					array(
						'class' => 'case-study-spotlight__image',
						'sizes' => '(min-width: 64rem) 48vw, 100vw',
					)
				); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- WordPress generates escaped image markup.
				?>
			</div>
		<?php endif; ?>

		<div class="case-study-spotlight__narrative">
			<div class="case-study-spotlight__narrative-section case-study-spotlight__narrative-section--challenge">
				<<?php echo esc_html( $child_heading_level ); ?> class="case-study-spotlight__subheading"><?php esc_html_e( 'The challenge', 'acf-module-workbench' ); ?></<?php echo esc_html( $child_heading_level ); ?>>
				<div class="case-study-spotlight__body"><?php echo wp_kses_post( $challenge ); ?></div>
			</div>

			<div class="case-study-spotlight__narrative-section case-study-spotlight__narrative-section--approach">
				<<?php echo esc_html( $child_heading_level ); ?> class="case-study-spotlight__subheading"><?php esc_html_e( 'The approach', 'acf-module-workbench' ); ?></<?php echo esc_html( $child_heading_level ); ?>>
				<div class="case-study-spotlight__body"><?php echo wp_kses_post( $approach ); ?></div>
			</div>
		</div>
	</div>

	<div class="case-study-spotlight__results">
		<<?php echo esc_html( $child_heading_level ); ?> class="case-study-spotlight__results-heading"><?php esc_html_e( 'What changed', 'acf-module-workbench' ); ?></<?php echo esc_html( $child_heading_level ); ?>>
		<dl class="case-study-spotlight__outcomes case-study-spotlight__outcomes--count-<?php echo esc_attr( (string) count( $outcomes ) ); ?>">
			<?php foreach ( $outcomes as $outcome_index => $outcome ) : ?>
				<div class="case-study-spotlight__outcome<?php echo count( $outcomes ) - 1 === $outcome_index ? ' case-study-spotlight__outcome--last' : ''; ?>">
					<dt class="case-study-spotlight__outcome-label"><?php echo esc_html( $outcome['label'] ); ?></dt>
					<dd class="case-study-spotlight__outcome-value"><?php echo esc_html( $outcome['value'] ); ?></dd>
					<?php if ( '' !== $outcome['detail'] ) : ?>
						<dd class="case-study-spotlight__outcome-detail"><?php echo esc_html( $outcome['detail'] ); ?></dd>
					<?php endif; ?>
				</div>
			<?php endforeach; ?>
		</dl>
	</div>

	<?php if ( $has_testimonial || null !== $case_study_link ) : ?>
		<footer class="case-study-spotlight__proof<?php echo $has_testimonial && null !== $case_study_link ? '' : ' case-study-spotlight__proof--single'; ?>">
			<?php if ( $has_testimonial ) : ?>
				<figure class="case-study-spotlight__testimonial">
					<blockquote class="case-study-spotlight__quote"><p><?php echo esc_html( $testimonial_quote ); ?></p></blockquote>
					<figcaption class="case-study-spotlight__attribution">
						<strong><?php echo esc_html( $testimonial_name ); ?></strong>
						<?php if ( '' !== $testimonial_role ) : ?><span><?php echo esc_html( $testimonial_role ); ?></span><?php endif; ?>
					</figcaption>
				</figure>
			<?php endif; ?>

			<?php if ( null !== $case_study_link ) : ?>
				<a class="case-study-spotlight__link"<?php if ( $is_editor_preview ) : ?> role="link" aria-disabled="true"<?php else : ?> href="<?php echo esc_url( $case_study_link['url'] ); ?>"<?php if ( '_blank' === $case_study_link['target'] ) : ?> target="_blank" rel="noopener noreferrer"<?php endif; ?><?php endif; ?>>
					<span><?php echo esc_html( $case_study_link['title'] ); ?></span>
					<span aria-hidden="true">&rarr;</span>
				</a>
			<?php endif; ?>
		</footer>
	<?php endif; ?>
</section>
