<?php
/**
 * Feature Cards block template.
 *
 * @package ACF_Module_Workbench
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$card_rows          = get_field( 'cards' );
$heading_level      = (string) get_field( 'heading_level' );
$cards              = array();
$featured_found     = false;
$allowed_headings   = array( 'h2', 'h3', 'h4' );
$allowed_icons      = array( 'palette', 'integrations', 'lock' );
$allowed_treatments = array( 'standard', 'positive', 'restricted' );

$heading_level = in_array( $heading_level, $allowed_headings, true ) ? $heading_level : 'h2';

if ( is_array( $card_rows ) ) {
	foreach ( array_slice( $card_rows, 0, 3 ) as $card_row ) {
		$label       = isset( $card_row['label'] ) ? trim( (string) $card_row['label'] ) : '';
		$title       = isset( $card_row['title'] ) ? trim( (string) $card_row['title'] ) : '';
		$description = isset( $card_row['description'] ) ? trim( (string) $card_row['description'] ) : '';
		$icon        = isset( $card_row['icon'] ) ? (string) $card_row['icon'] : '';
		$treatment   = isset( $card_row['treatment'] ) ? (string) $card_row['treatment'] : '';
		$icon        = in_array( $icon, $allowed_icons, true ) ? $icon : 'palette';
		$treatment   = in_array( $treatment, $allowed_treatments, true ) ? $treatment : 'standard';

		if ( '' === $label && '' === $title && '' === $description ) {
			continue;
		}

		$is_featured = ! $featured_found && isset( $card_row['featured'] ) && '1' === (string) $card_row['featured'];

		if ( $is_featured ) {
			$featured_found = true;
		}

		$cards[] = array(
			'label'       => $label,
			'title'       => $title,
			'description' => $description,
			'icon'        => $icon,
			'treatment'   => $treatment,
			'featured'    => $is_featured,
		);
	}
}

if ( empty( $cards ) ) {
	return;
}

$wrapper_classes    = sprintf( 'feature-cards feature-cards--count-%d', count( $cards ) );
$wrapper_attributes = get_block_wrapper_attributes(
	array(
		'class' => $wrapper_classes,
	)
);
?>
<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?>>
	<div class="feature-cards__grid">
		<?php foreach ( $cards as $card ) : ?>
			<?php
			$heading_id = '' !== $card['title'] ? wp_unique_id( 'feature-cards-heading-' ) : '';
			$classes    = sprintf( 'feature-cards__item feature-cards__item--%s', $card['treatment'] );

			if ( $card['featured'] ) {
				$classes .= ' feature-cards__item--emphasized';
			}

			$element    = '' !== $heading_id ? 'article' : 'div';
			$labelledby = '' !== $heading_id ? sprintf( ' aria-labelledby="%s"', esc_attr( $heading_id ) ) : '';
			?>
			<<?php echo esc_html( $element ); ?> class="<?php echo esc_attr( $classes ); ?>"<?php echo $labelledby; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Escaped above. ?>>
				<?php if ( '' !== $card['label'] ) : ?>
					<p class="feature-cards__label">
						<?php if ( 'palette' === $card['icon'] ) : ?>
							<svg class="feature-cards__icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
								<path d="M12 3a9 9 0 1 0 0 18h1.2a2 2 0 0 0 1.86-2.73l-.12-.3A2 2 0 0 1 16.8 15H18a3 3 0 0 0 3-3 9 9 0 0 0-9-9Z"></path>
								<circle cx="7.5" cy="10.5" r=".75"></circle>
								<circle cx="10" cy="7" r=".75"></circle>
								<circle cx="14" cy="7.5" r=".75"></circle>
							</svg>
						<?php elseif ( 'integrations' === $card['icon'] ) : ?>
							<svg class="feature-cards__icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
								<path d="m16 3 3 3-3 3"></path>
								<path d="M5 6h14"></path>
								<path d="m8 21-3-3 3-3"></path>
								<path d="M19 18H5"></path>
								<path d="M5 6v5h5M19 18v-5h-5"></path>
							</svg>
						<?php else : ?>
							<svg class="feature-cards__icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
								<rect x="5" y="10" width="14" height="11" rx="2"></rect>
								<path d="M8 10V7a4 4 0 0 1 8 0v3M12 15v2"></path>
							</svg>
						<?php endif; ?>
						<span><?php echo esc_html( $card['label'] ); ?></span>
					</p>
				<?php endif; ?>

				<?php if ( '' !== $card['title'] ) : ?>
					<<?php echo esc_html( $heading_level ); ?> class="feature-cards__title" id="<?php echo esc_attr( $heading_id ); ?>"><?php echo esc_html( $card['title'] ); ?></<?php echo esc_html( $heading_level ); ?>>
				<?php endif; ?>

				<?php if ( '' !== $card['description'] ) : ?>
					<p class="feature-cards__description"><?php echo esc_html( $card['description'] ); ?></p>
				<?php endif; ?>
			</<?php echo esc_html( $element ); ?>>
		<?php endforeach; ?>
	</div>
</div>
