<?php
/**
 * Project Gallery block template.
 *
 * @package ACF_Module_Workbench
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$eyebrow           = trim( (string) get_field( 'eyebrow' ) );
$heading           = trim( (string) get_field( 'heading' ) );
$heading_level     = (string) get_field( 'heading_level' );
$introduction      = trim( (string) get_field( 'introduction' ) );
$image_shape       = (string) get_field( 'image_shape' );
$image_values      = get_field( 'images' );
$gallery_link      = get_field( 'gallery_link' );
$is_editor_preview = ! empty( $is_preview ) || is_admin() || ( defined( 'REST_REQUEST' ) && REST_REQUEST );
$allowed_headings  = array( 'h2', 'h3', 'h4' );
$allowed_shapes    = array( 'landscape', 'square' );
$image_ids         = array();

$heading_level = in_array( $heading_level, $allowed_headings, true ) ? $heading_level : 'h2';
$image_shape   = in_array( $image_shape, $allowed_shapes, true ) ? $image_shape : 'landscape';

if ( is_array( $image_values ) ) {
	foreach ( array_slice( $image_values, 0, 12 ) as $image_value ) {
		$image_id = is_array( $image_value ) && isset( $image_value['ID'] ) ? absint( $image_value['ID'] ) : absint( $image_value );

		if ( $image_id && wp_attachment_is_image( $image_id ) ) {
			$image_ids[] = $image_id;
		}
	}
}

$image_ids = array_values( array_unique( $image_ids ) );

/**
 * Normalize the optional ACF link field.
 *
 * @param mixed $link Raw ACF link value.
 * @return array{url:string,title:string,target:string}|null
 */
$normalize_link = static function ( $link ): ?array {
	if ( ! is_array( $link ) ) {
		return null;
	}

	$url    = isset( $link['url'] ) ? trim( (string) $link['url'] ) : '';
	$title  = isset( $link['title'] ) ? trim( (string) $link['title'] ) : '';
	$target = isset( $link['target'] ) && '_blank' === $link['target'] ? '_blank' : '';

	if ( '' === $url || '' === $title ) {
		return null;
	}

	return array(
		'url'    => $url,
		'title'  => $title,
		'target' => $target,
	);
};

$gallery_link = $normalize_link( $gallery_link );
$is_complete  = '' !== $heading && count( $image_ids ) >= 3;

if ( ! $is_complete ) {
	if ( ! $is_editor_preview ) {
		return;
	}

	$wrapper_attributes = get_block_wrapper_attributes(
		array( 'class' => 'project-gallery project-gallery--incomplete' )
	);
	?>
	<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?>>
		<p class="project-gallery__editor-guidance"><?php esc_html_e( 'Project Gallery: add a heading and at least three images to preview this block.', 'acf-module-workbench' ); ?></p>
	</div>
	<?php
	return;
}

$gallery_count      = count( $image_ids );
$carousel_id        = wp_unique_id( 'project-gallery-carousel-' );
$heading_id         = wp_unique_id( 'project-gallery-heading-' );
$dialog_title_id    = wp_unique_id( 'project-gallery-dialog-title-' );
$wrapper_attributes = get_block_wrapper_attributes(
	array(
		'class' => sprintf(
			'project-gallery project-gallery--%1$s project-gallery--count-%2$d',
			$image_shape,
			$gallery_count
		),
	)
);
?>
<section <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?> aria-labelledby="<?php echo esc_attr( $heading_id ); ?>" data-project-gallery<?php if ( $is_editor_preview ) : ?> data-editor-preview="true"<?php endif; ?>>
	<header class="project-gallery__header">
		<div class="project-gallery__heading-group">
			<?php if ( '' !== $eyebrow ) : ?>
				<p class="project-gallery__eyebrow"><?php echo esc_html( $eyebrow ); ?></p>
			<?php endif; ?>

			<<?php echo esc_html( $heading_level ); ?> class="project-gallery__heading" id="<?php echo esc_attr( $heading_id ); ?>"><?php echo esc_html( $heading ); ?></<?php echo esc_html( $heading_level ); ?>>
		</div>

		<?php if ( '' !== $introduction ) : ?>
			<p class="project-gallery__introduction"><?php echo esc_html( $introduction ); ?></p>
		<?php endif; ?>
	</header>

	<div class="project-gallery__carousel" data-project-gallery-carousel>
		<div class="project-gallery__viewport" data-project-gallery-viewport>
			<ul class="project-gallery__grid" id="<?php echo esc_attr( $carousel_id ); ?>" role="list">
				<?php foreach ( $image_ids as $image_index => $image_id ) : ?>
					<?php
					$full_image_url = wp_get_attachment_image_url( $image_id, 'full' );
					$caption        = trim( (string) wp_get_attachment_caption( $image_id ) );
					$alt            = trim( (string) get_post_meta( $image_id, '_wp_attachment_image_alt', true ) );
					$position       = $image_index + 1;
					$slide_id       = $carousel_id . '-slide-' . $position;
					$item_classes   = array( 'project-gallery__item' );

					if ( ! $full_image_url ) {
						continue;
					}

					if ( 1 === $position ) {
						$item_classes[] = 'project-gallery__item--primary';
					}

					if ( 1 === $gallery_count % 2 && $gallery_count === $position ) {
						$item_classes[] = 'project-gallery__item--mobile-full';
					}

					if ( in_array( $gallery_count, array( 4, 7, 10 ), true ) && $position > $gallery_count - 4 ) {
						$item_classes[] = 'project-gallery__item--desktop-wide';
					}

					if ( in_array( $gallery_count, array( 5, 8, 11 ), true ) && $position > $gallery_count - 2 ) {
						$item_classes[] = 'project-gallery__item--desktop-wide';
					}

					$trigger_label = '' !== $alt || '' !== $caption
						? sprintf(
							/* translators: 1: current image number, 2: total images, 3: image description. */
							__( 'View image %1$d of %2$d larger: %3$s', 'acf-module-workbench' ),
							$position,
							$gallery_count,
							'' !== $alt ? $alt : $caption
						)
						: sprintf(
							/* translators: 1: current image number, 2: total images. */
							__( 'View image %1$d of %2$d larger', 'acf-module-workbench' ),
							$position,
							$gallery_count
						);
					?>
					<li class="<?php echo esc_attr( implode( ' ', $item_classes ) ); ?>" id="<?php echo esc_attr( $slide_id ); ?>"<?php if ( $is_editor_preview && 0 < $image_index ) : ?> hidden<?php endif; ?>>
						<figure class="project-gallery__figure">
							<a class="project-gallery__image-link"<?php if ( $is_editor_preview ) : ?> role="link" aria-disabled="true"<?php else : ?> href="<?php echo esc_url( $full_image_url ); ?>" data-project-gallery-trigger data-gallery-index="<?php echo esc_attr( (string) $image_index ); ?>"<?php endif; ?> aria-label="<?php echo esc_attr( $trigger_label ); ?>">
								<?php
								echo wp_get_attachment_image(
									$image_id,
									'large',
									false,
									array(
										'class' => 'project-gallery__image',
										'sizes' => '(min-width: 64rem) 72rem, 100vw',
									)
								); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- WordPress generates escaped image markup.
								?>
								<span class="project-gallery__zoom" aria-hidden="true"><?php esc_html_e( 'View larger', 'acf-module-workbench' ); ?> <span>+</span></span>
							</a>
							<?php if ( '' !== $caption ) : ?>
								<figcaption class="project-gallery__caption"><?php echo esc_html( $caption ); ?></figcaption>
							<?php endif; ?>
						</figure>
					</li>
				<?php endforeach; ?>
			</ul>
		</div>

		<div class="project-gallery__carousel-controls" role="group" aria-label="<?php esc_attr_e( 'Gallery navigation', 'acf-module-workbench' ); ?>" data-project-gallery-controls<?php if ( ! $is_editor_preview ) : ?> hidden<?php endif; ?>>
			<button type="button" data-project-gallery-slide-previous<?php if ( $is_editor_preview ) : ?> disabled<?php endif; ?>><span aria-hidden="true">&larr;</span> <?php esc_html_e( 'Previous', 'acf-module-workbench' ); ?></button>
			<p aria-live="polite" aria-atomic="true" data-project-gallery-slide-status data-status-template="<?php esc_attr_e( 'Image %1$d of %2$d', 'acf-module-workbench' ); ?>"><?php if ( $is_editor_preview ) : ?><?php echo esc_html( sprintf( /* translators: 1: current image number, 2: total images. */ __( 'Image %1$d of %2$d', 'acf-module-workbench' ), 1, $gallery_count ) ); ?><?php endif; ?></p>
			<button type="button" data-project-gallery-slide-next<?php if ( $is_editor_preview ) : ?> disabled<?php endif; ?>><?php esc_html_e( 'Next', 'acf-module-workbench' ); ?> <span aria-hidden="true">&rarr;</span></button>
		</div>

		<nav class="project-gallery__thumbnail-navigation" aria-label="<?php esc_attr_e( 'Choose a gallery image', 'acf-module-workbench' ); ?>" data-project-gallery-thumbnails<?php if ( ! $is_editor_preview ) : ?> hidden<?php endif; ?>>
			<ol class="project-gallery__thumbnails">
				<?php foreach ( $image_ids as $image_index => $image_id ) : ?>
					<?php
					$position         = $image_index + 1;
					$alt              = trim( (string) get_post_meta( $image_id, '_wp_attachment_image_alt', true ) );
					$caption          = trim( (string) wp_get_attachment_caption( $image_id ) );
					$thumbnail_label  = '' !== $alt ? $alt : $caption;
					$thumbnail_label  = '' !== $thumbnail_label
						? sprintf(
							/* translators: 1: current image number, 2: total images, 3: image description. */
							__( 'Show image %1$d of %2$d: %3$s', 'acf-module-workbench' ),
							$position,
							$gallery_count,
							$thumbnail_label
						)
						: sprintf(
							/* translators: 1: current image number, 2: total images. */
							__( 'Show image %1$d of %2$d', 'acf-module-workbench' ),
							$position,
							$gallery_count
						);
					?>
					<li>
						<button type="button" aria-controls="<?php echo esc_attr( $carousel_id . '-slide-' . $position ); ?>" aria-label="<?php echo esc_attr( $thumbnail_label ); ?>" data-project-gallery-thumbnail data-gallery-index="<?php echo esc_attr( (string) $image_index ); ?>"<?php if ( $is_editor_preview ) : ?> disabled<?php if ( 0 === $image_index ) : ?> aria-current="true"<?php endif; ?><?php endif; ?>>
							<?php
							echo wp_get_attachment_image(
								$image_id,
								'thumbnail',
								false,
								array(
									'alt'   => '',
									'class' => 'project-gallery__thumbnail-image',
								)
							); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- WordPress generates escaped image markup.
							?>
						</button>
					</li>
				<?php endforeach; ?>
			</ol>
		</nav>
	</div>

	<?php if ( null !== $gallery_link ) : ?>
		<footer class="project-gallery__footer">
			<a class="project-gallery__cta"<?php if ( $is_editor_preview ) : ?> role="link" aria-disabled="true"<?php else : ?> href="<?php echo esc_url( $gallery_link['url'] ); ?>"<?php if ( '_blank' === $gallery_link['target'] ) : ?> target="_blank" rel="noopener noreferrer"<?php endif; ?><?php endif; ?>>
				<span class="project-gallery__cta-label"><?php echo esc_html( $gallery_link['title'] ); ?></span>
				<span class="project-gallery__cta-icon" aria-hidden="true">&rarr;</span>
			</a>
		</footer>
	<?php endif; ?>

	<?php if ( ! $is_editor_preview ) : ?>
		<dialog class="project-gallery__dialog" aria-labelledby="<?php echo esc_attr( $dialog_title_id ); ?>" data-project-gallery-dialog data-status-template="<?php esc_attr_e( 'Image %1$d of %2$d', 'acf-module-workbench' ); ?>">
			<div class="project-gallery__dialog-inner">
				<span class="project-gallery__visually-hidden" id="<?php echo esc_attr( $dialog_title_id ); ?>"><?php esc_html_e( 'Expanded project image', 'acf-module-workbench' ); ?></span>
				<button class="project-gallery__dialog-close" type="button" data-project-gallery-close aria-label="<?php esc_attr_e( 'Close expanded image', 'acf-module-workbench' ); ?>">&times;</button>
				<figure class="project-gallery__dialog-figure">
					<img class="project-gallery__dialog-image" alt="" data-project-gallery-image>
					<figcaption class="project-gallery__dialog-caption" data-project-gallery-caption hidden></figcaption>
				</figure>
				<div class="project-gallery__dialog-controls">
					<button type="button" data-project-gallery-previous><?php esc_html_e( 'Previous', 'acf-module-workbench' ); ?></button>
					<p aria-live="polite" aria-atomic="true" data-project-gallery-status></p>
					<button type="button" data-project-gallery-next><?php esc_html_e( 'Next', 'acf-module-workbench' ); ?></button>
				</div>
			</div>
		</dialog>
	<?php endif; ?>
</section>
