<?php
/**
 * Proof Logos block template.
 *
 * @package ACF_Module_Workbench
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$eyebrow           = trim( (string) get_field( 'eyebrow' ) );
$heading           = trim( (string) get_field( 'heading' ) );
$heading_level     = (string) get_field( 'heading_level' );
$introduction      = trim( (string) get_field( 'introduction' ) );
$logo_treatment    = (string) get_field( 'logo_treatment' );
$layout_density    = (string) get_field( 'layout_density' );
$logo_rows         = get_field( 'logos' );
$cta               = get_field( 'cta' );
$is_editor_preview = ! empty( $is_preview );
$allowed_headings  = array( 'h2', 'h3', 'h4' );
$allowed_treatments = array( 'original', 'grayscale', 'monochrome' );
$allowed_densities = array( 'compact', 'standard', 'spacious' );
$allowed_scales    = array( '80', '90', '100', '110', '120' );
$logos             = array();

$heading_level  = in_array( $heading_level, $allowed_headings, true ) ? $heading_level : 'h2';
$logo_treatment = in_array( $logo_treatment, $allowed_treatments, true ) ? $logo_treatment : 'grayscale';
$layout_density = in_array( $layout_density, $allowed_densities, true ) ? $layout_density : 'standard';

/**
 * Normalize the optional ACF link field.
 *
 * @param mixed $link Raw ACF link value.
 * @return array{url:string,title:string,target:string}|null
 */
$normalize_link = static function ( $link ): ?array {
	if ( ! is_array( $link ) ) {
		return null;
	}

	$url    = isset( $link['url'] ) ? esc_url_raw( trim( (string) $link['url'] ) ) : '';
	$title  = isset( $link['title'] ) ? trim( (string) $link['title'] ) : '';
	$target = isset( $link['target'] ) && '_blank' === $link['target'] ? '_blank' : '';

	if ( '' === $url || '' === $title ) {
		return null;
	}

	return array(
		'url'    => $url,
		'title'  => $title,
		'target' => $target,
	);
};

/**
 * Render a logo image from any image attachment, including SVG attachments.
 *
 * @param int    $attachment_id Attachment ID.
 * @param string $class_name Image class.
 * @return string
 */
$render_logo_image = static function ( int $attachment_id, string $class_name ): string {
	$mime_type = (string) get_post_mime_type( $attachment_id );
	$image_url = wp_get_attachment_url( $attachment_id );

	if ( '' === $mime_type || ! str_starts_with( $mime_type, 'image/' ) || ! $image_url ) {
		return '';
	}

	if ( 'image/svg+xml' !== $mime_type ) {
		$image_markup = wp_get_attachment_image(
			$attachment_id,
			'medium',
			false,
			array(
				'alt'     => '',
				'class'   => $class_name,
				'loading' => 'lazy',
				'sizes'   => '(min-width: 64rem) 10rem, (min-width: 42rem) 8rem, 9rem',
			)
		);

		return is_string( $image_markup ) ? $image_markup : '';
	}

	return sprintf(
		'<img src="%1$s" class="%2$s" alt="" loading="lazy" decoding="async">',
		esc_url( $image_url ),
		esc_attr( $class_name )
	);
};

if ( is_array( $logo_rows ) ) {
	foreach ( array_slice( $logo_rows, 0, 12 ) as $logo_row ) {
		if ( ! is_array( $logo_row ) ) {
			continue;
		}

		$attachment_id = isset( $logo_row['logo'] ) ? absint( $logo_row['logo'] ) : 0;
		$name          = isset( $logo_row['name'] ) ? trim( (string) $logo_row['name'] ) : '';
		$link          = isset( $logo_row['link'] ) ? $normalize_link( $logo_row['link'] ) : null;
		$scale         = isset( $logo_row['visual_scale'] ) ? (string) $logo_row['visual_scale'] : '100';
		$treatment     = isset( $logo_row['treatment'] ) ? (string) $logo_row['treatment'] : 'inherit';
		$mime_type     = $attachment_id ? (string) get_post_mime_type( $attachment_id ) : '';

		if ( ! $attachment_id || '' === $name || ! str_starts_with( $mime_type, 'image/' ) ) {
			continue;
		}

		$scale     = in_array( $scale, $allowed_scales, true ) ? $scale : '100';
		$treatment = in_array( $treatment, array_merge( array( 'inherit' ), $allowed_treatments ), true ) ? $treatment : 'inherit';

		$logos[] = array(
			'id'        => $attachment_id,
			'name'      => $name,
			'link'      => $link,
			'scale'     => $scale,
			'treatment' => 'inherit' === $treatment ? $logo_treatment : $treatment,
		);
	}
}

$cta              = $normalize_link( $cta );
$has_minimum_data = '' !== $heading && count( $logos ) >= 2;

if ( ! $has_minimum_data ) {
	if ( ! $is_editor_preview ) {
		return;
	}

	$wrapper_attributes = get_block_wrapper_attributes(
		array( 'class' => 'proof-logos proof-logos--incomplete' )
	);
	?>
	<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?>>
		<p class="proof-logos__editor-guidance"><?php esc_html_e( 'Proof Logos: add a heading and at least two complete logos to preview this block.', 'acf-module-workbench' ); ?></p>
	</div>
	<?php
	return;
}

$heading_id         = wp_unique_id( 'proof-logos-heading-' );
$wrapper_attributes = get_block_wrapper_attributes(
	array(
		'class' => sprintf(
			'proof-logos proof-logos--%1$s proof-logos--density-%2$s proof-logos--count-%3$d',
			$logo_treatment,
			$layout_density,
			count( $logos )
		),
	)
);
?>
<section <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?> aria-labelledby="<?php echo esc_attr( $heading_id ); ?>">
	<header class="proof-logos__header">
		<div class="proof-logos__heading-group">
			<?php if ( '' !== $eyebrow ) : ?>
				<p class="proof-logos__eyebrow"><?php echo esc_html( $eyebrow ); ?></p>
			<?php endif; ?>

			<<?php echo esc_html( $heading_level ); ?> class="proof-logos__heading" id="<?php echo esc_attr( $heading_id ); ?>"><?php echo esc_html( $heading ); ?></<?php echo esc_html( $heading_level ); ?>>
		</div>

		<?php if ( '' !== $introduction ) : ?>
			<p class="proof-logos__introduction"><?php echo esc_html( $introduction ); ?></p>
		<?php endif; ?>
	</header>

	<ul class="proof-logos__list" role="list">
		<?php foreach ( $logos as $logo_index => $logo ) : ?>
			<?php
			$image_markup = $render_logo_image( $logo['id'], 'proof-logos__image' );

			if ( '' === $image_markup ) {
				continue;
			}

			$item_style = '--proof-logos-item-scale: ' . ( (float) $logo['scale'] / 100 ) . ';';
			$position   = $logo_index + 1;
			$logo_count = count( $logos );
			$classes    = array( 'proof-logos__item', 'proof-logos__item--' . $logo['treatment'] );

			if ( 1 === $logo_count % 2 && $logo_count === $position ) {
				$classes[] = 'proof-logos__item--mobile-full';
			}

			if ( in_array( $logo_count, array( 4, 7, 10 ), true ) && $logo_count === $position ) {
				$classes[] = 'proof-logos__item--tablet-full';
			}

			if ( in_array( $logo_count, array( 5, 8, 11 ), true ) && $position > $logo_count - 2 ) {
				$classes[] = 'proof-logos__item--tablet-half';
			}

			if ( in_array( $logo_count, array( 5, 9 ), true ) && $logo_count === $position ) {
				$classes[] = 'proof-logos__item--desktop-full';
			}

			if ( in_array( $logo_count, array( 6, 10 ), true ) && $position > $logo_count - 2 ) {
				$classes[] = 'proof-logos__item--desktop-half';
			}

			if ( in_array( $logo_count, array( 7, 11 ), true ) && $position > $logo_count - 3 ) {
				$classes[] = 'proof-logos__item--desktop-third';
			}
			?>
			<li class="<?php echo esc_attr( implode( ' ', $classes ) ); ?>" style="<?php echo esc_attr( $item_style ); ?>">
				<?php if ( null !== $logo['link'] && ! $is_editor_preview ) : ?>
					<a class="proof-logos__link" href="<?php echo esc_url( $logo['link']['url'] ); ?>"<?php if ( '_blank' === $logo['link']['target'] ) : ?> target="_blank" rel="noopener noreferrer"<?php endif; ?> aria-label="<?php echo esc_attr( sprintf( /* translators: %s: organization name. */ __( 'Visit %s', 'acf-module-workbench' ), $logo['name'] ) ); ?>">
						<?php echo $image_markup; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Image markup is escaped by WordPress or this template. ?>
						<span class="proof-logos__name"><?php echo esc_html( $logo['name'] ); ?></span>
					</a>
				<?php else : ?>
					<div class="proof-logos__mark" aria-label="<?php echo esc_attr( $logo['name'] ); ?>">
						<?php echo $image_markup; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Image markup is escaped by WordPress or this template. ?>
						<span class="proof-logos__name"><?php echo esc_html( $logo['name'] ); ?></span>
					</div>
				<?php endif; ?>
			</li>
		<?php endforeach; ?>
	</ul>

	<?php if ( null !== $cta ) : ?>
		<footer class="proof-logos__footer">
			<a class="proof-logos__cta"<?php if ( $is_editor_preview ) : ?> role="link" aria-disabled="true"<?php else : ?> href="<?php echo esc_url( $cta['url'] ); ?>"<?php if ( '_blank' === $cta['target'] ) : ?> target="_blank" rel="noopener noreferrer"<?php endif; ?><?php endif; ?>>
				<span class="proof-logos__cta-label"><?php echo esc_html( $cta['title'] ); ?></span>
				<span class="proof-logos__cta-icon" aria-hidden="true">&rarr;</span>
			</a>
		</footer>
	<?php endif; ?>
</section>
