<?php
/**
 * Open Positions block template.
 *
 * @package ACF_Module_Workbench
 */

use function ACF_Module_Workbench\Open_Positions\get_jobs;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$eyebrow           = trim( (string) get_field( 'eyebrow' ) );
$heading           = trim( (string) get_field( 'heading' ) );
$introduction      = trim( (string) get_field( 'introduction' ) );
$heading_level     = (string) get_field( 'heading_level' );
$board_token       = strtolower( trim( (string) get_field( 'board_token' ) ) );
$maximum_jobs      = absint( get_field( 'maximum_jobs' ) );
$link_label        = trim( (string) get_field( 'link_label' ) );
$empty_message     = trim( (string) get_field( 'empty_message' ) );
$is_editor_preview = ! empty( $is_preview );
$allowed_headings  = array( 'h2', 'h3', 'h4' );
$job_headings      = array( 'h2' => 'h3', 'h3' => 'h4', 'h4' => 'h5' );

$heading_level = in_array( $heading_level, $allowed_headings, true ) ? $heading_level : 'h2';
$job_heading   = $job_headings[ $heading_level ];
$maximum_jobs  = min( 12, max( 1, $maximum_jobs ?: 6 ) );
$link_label    = '' !== $link_label ? $link_label : __( 'View role', 'acf-module-workbench' );
$empty_message = '' !== $empty_message ? $empty_message : __( 'There are no open positions right now. Please check back soon.', 'acf-module-workbench' );
$is_complete   = '' !== $heading && 1 === preg_match( '/^[a-z0-9_-]{1,100}$/', $board_token );

if ( ! $is_complete ) {
	if ( ! $is_editor_preview ) {
		return;
	}

	$wrapper_attributes = get_block_wrapper_attributes(
		array( 'class' => 'open-positions open-positions--incomplete' )
	);
	?>
	<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?>>
		<p class="open-positions__editor-guidance">
			<?php esc_html_e( 'Open Positions: add a heading and valid Greenhouse board token to preview this block.', 'acf-module-workbench' ); ?>
		</p>
	</div>
	<?php
	return;
}

$result = get_jobs( $board_token );
$jobs   = is_wp_error( $result ) ? array() : array_slice( $result['jobs'], 0, $maximum_jobs );

$heading_id         = wp_unique_id( 'open-positions-heading-' );
$wrapper_attributes = get_block_wrapper_attributes(
	array(
		'class' => sprintf( 'open-positions open-positions--count-%d', count( $jobs ) ),
	)
);
?>
<section <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?> aria-labelledby="<?php echo esc_attr( $heading_id ); ?>">
	<header class="open-positions__header">
		<?php if ( '' !== $eyebrow ) : ?>
			<p class="open-positions__eyebrow"><?php echo esc_html( $eyebrow ); ?></p>
		<?php endif; ?>

		<<?php echo esc_html( $heading_level ); ?> class="open-positions__heading" id="<?php echo esc_attr( $heading_id ); ?>"><?php echo esc_html( $heading ); ?></<?php echo esc_html( $heading_level ); ?>>

		<?php if ( '' !== $introduction ) : ?>
			<p class="open-positions__introduction"><?php echo esc_html( $introduction ); ?></p>
		<?php endif; ?>
	</header>

	<?php if ( ! empty( $jobs ) ) : ?>
		<ul class="open-positions__jobs" role="list">
			<?php foreach ( $jobs as $job ) : ?>
				<li class="open-positions__job">
					<a class="open-positions__job-link"<?php if ( $is_editor_preview ) : ?> role="link" aria-disabled="true"<?php else : ?> href="<?php echo esc_url( $job['url'] ); ?>"<?php endif; ?>>
						<div class="open-positions__job-content">
							<<?php echo esc_html( $job_heading ); ?> class="open-positions__job-title"><?php echo esc_html( $job['title'] ); ?></<?php echo esc_html( $job_heading ); ?>>

							<?php if ( '' !== $job['location'] ) : ?>
								<p class="open-positions__job-meta">
									<span><?php echo esc_html( $job['location'] ); ?></span>
								</p>
							<?php endif; ?>
						</div>

						<span class="open-positions__job-action">
							<?php echo esc_html( $link_label ); ?>
							<svg viewBox="0 0 20 20" aria-hidden="true" focusable="false"><path d="M4 10h11m-4-4 4 4-4 4"></path></svg>
						</span>
					</a>
				</li>
			<?php endforeach; ?>
		</ul>
	<?php else : ?>
		<div class="open-positions__empty">
			<p><?php echo esc_html( $empty_message ); ?></p>
			<?php if ( $is_editor_preview && is_wp_error( $result ) ) : ?>
				<p class="open-positions__editor-status"><?php esc_html_e( 'Editor note: the configured Greenhouse board could not be loaded. Check the board token and API availability.', 'acf-module-workbench' ); ?></p>
			<?php endif; ?>
		</div>
	<?php endif; ?>
</section>
