<?php
/**
 * Testimonials block template.
 *
 * @package ACF_Module_Workbench
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$eyebrow           = trim( (string) get_field( 'eyebrow' ) );
$heading           = trim( (string) get_field( 'heading' ) );
$introduction      = trim( (string) get_field( 'introduction' ) );
$heading_level     = (string) get_field( 'heading_level' );
$testimonial_rows = get_field( 'testimonial_rows' );
$is_editor_preview = ! empty( $is_preview );
$allowed_headings  = array( 'h2', 'h3', 'h4' );
$rows              = array();

$heading_level = in_array( $heading_level, $allowed_headings, true ) ? $heading_level : 'h2';

/**
 * Normalize one authored testimonial.
 *
 * @param array<string, mixed> $testimonial Raw ACF values.
 * @return array<string, mixed>|null
 */
$normalize_testimonial = static function ( array $testimonial ): ?array {
	$quote        = isset( $testimonial['quote'] ) ? trim( (string) $testimonial['quote'] ) : '';
	$name         = isset( $testimonial['name'] ) ? trim( (string) $testimonial['name'] ) : '';
	$role         = isset( $testimonial['role'] ) ? trim( (string) $testimonial['role'] ) : '';
	$organization = isset( $testimonial['organization'] ) ? trim( (string) $testimonial['organization'] ) : '';
	$detail       = isset( $testimonial['detail'] ) ? trim( (string) $testimonial['detail'] ) : '';
	$image_id     = isset( $testimonial['portrait'] ) ? absint( $testimonial['portrait'] ) : 0;
	$initials     = '';

	if ( '' === $quote || '' === $name ) {
		return null;
	}

	$image_id   = $image_id && wp_attachment_is_image( $image_id ) ? $image_id : 0;
	$name_parts = preg_split( '/\s+/u', $name, -1, PREG_SPLIT_NO_EMPTY );
	$name_parts = is_array( $name_parts ) ? $name_parts : array();
	$initial_parts = count( $name_parts ) > 1
		? array( $name_parts[0], $name_parts[ count( $name_parts ) - 1 ] )
		: $name_parts;

	foreach ( $initial_parts as $initial_part ) {
		$initials .= function_exists( 'mb_substr' ) ? mb_substr( $initial_part, 0, 1 ) : substr( $initial_part, 0, 1 );
	}

	$initials = function_exists( 'mb_strtoupper' ) ? mb_strtoupper( $initials ) : strtoupper( $initials );

	return array(
		'quote'        => $quote,
		'name'         => $name,
		'role'         => $role,
		'organization' => $organization,
		'detail'       => $detail,
		'image_id'     => $image_id,
		'initials'     => $initials,
	);
};

if ( is_array( $testimonial_rows ) ) {
	foreach ( $testimonial_rows as $testimonial_row ) {
		if ( ! is_array( $testimonial_row ) || empty( $testimonial_row['acf_fc_layout'] ) ) {
			continue;
		}

		if ( 'standard_row' === $testimonial_row['acf_fc_layout'] ) {
			$standard_rows = isset( $testimonial_row['testimonials'] ) && is_array( $testimonial_row['testimonials'] )
				? array_slice( $testimonial_row['testimonials'], 0, 3 )
				: array();
			$testimonials = array();

			foreach ( $standard_rows as $standard_row ) {
				$testimonial = is_array( $standard_row ) ? $normalize_testimonial( $standard_row ) : null;

				if ( null !== $testimonial ) {
					$testimonials[] = $testimonial;
				}
			}

			if ( ! empty( $testimonials ) ) {
				$rows[] = array(
					'layout'       => 'standard',
					'testimonials' => $testimonials,
				);
			}
		}

		if ( 'featured_row' === $testimonial_row['acf_fc_layout'] ) {
			$testimonial = $normalize_testimonial( $testimonial_row );

			if ( null !== $testimonial ) {
				$rows[] = array(
					'layout'      => 'featured',
					'testimonial' => $testimonial,
				);
			}
		}
	}
}

if ( '' === $heading || empty( $rows ) ) {
	if ( ! $is_editor_preview ) {
		return;
	}

	$wrapper_attributes = get_block_wrapper_attributes(
		array( 'class' => 'testimonials testimonials--incomplete' )
	);
	?>
	<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?>>
		<p class="testimonials__editor-guidance"><?php esc_html_e( 'Testimonials: add a heading and at least one complete testimonial to preview this block.', 'acf-module-workbench' ); ?></p>
	</div>
	<?php
	return;
}

$heading_id         = wp_unique_id( 'testimonials-heading-' );
$wrapper_attributes = get_block_wrapper_attributes(
	array( 'class' => 'testimonials' )
);
?>
<section <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?> aria-labelledby="<?php echo esc_attr( $heading_id ); ?>">
	<header class="testimonials__header">
		<div class="testimonials__heading-group">
			<<?php echo esc_html( $heading_level ); ?> class="testimonials__heading" id="<?php echo esc_attr( $heading_id ); ?>"><?php echo esc_html( $heading ); ?></<?php echo esc_html( $heading_level ); ?>>
		</div>

		<?php if ( '' !== $eyebrow || '' !== $introduction ) : ?>
			<div class="testimonials__introduction-group">
				<?php if ( '' !== $eyebrow ) : ?>
					<p class="testimonials__eyebrow"><?php echo esc_html( $eyebrow ); ?></p>
				<?php endif; ?>

				<?php if ( '' !== $introduction ) : ?>
					<p class="testimonials__introduction"><?php echo esc_html( $introduction ); ?></p>
				<?php endif; ?>
			</div>
		<?php endif; ?>
	</header>

	<div class="testimonials__rows">
		<?php foreach ( $rows as $row ) : ?>
			<?php if ( 'standard' === $row['layout'] ) : ?>
				<ul class="testimonials__standard-row testimonials__standard-row--count-<?php echo esc_attr( (string) count( $row['testimonials'] ) ); ?>" role="list">
					<?php foreach ( $row['testimonials'] as $testimonial ) : ?>
						<li class="testimonials__standard-item">
							<figure class="testimonials__card">
								<blockquote class="testimonials__quote testimonials__quote--standard">
									<p><?php echo esc_html( $testimonial['quote'] ); ?></p>
								</blockquote>

								<figcaption class="testimonials__attribution">
									<div class="testimonials__portrait testimonials__portrait--standard">
										<?php if ( $testimonial['image_id'] ) : ?>
											<?php
											echo wp_get_attachment_image(
												$testimonial['image_id'],
												'thumbnail',
												false,
												array( 'class' => 'testimonials__portrait-image' )
											); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- WordPress generates escaped image markup.
											?>
										<?php else : ?>
											<span class="testimonials__portrait-fallback" aria-hidden="true"><?php echo esc_html( $testimonial['initials'] ); ?></span>
										<?php endif; ?>
									</div>

									<div class="testimonials__attribution-copy">
										<strong class="testimonials__name"><?php echo esc_html( $testimonial['name'] ); ?></strong>
										<?php if ( '' !== $testimonial['role'] || '' !== $testimonial['organization'] ) : ?>
											<p class="testimonials__context">
												<?php echo esc_html( $testimonial['role'] ); ?><?php if ( '' !== $testimonial['role'] && '' !== $testimonial['organization'] ) : ?>, <?php endif; ?><?php echo esc_html( $testimonial['organization'] ); ?>
											</p>
										<?php endif; ?>
									</div>
								</figcaption>
							</figure>
						</li>
					<?php endforeach; ?>
				</ul>
			<?php else : ?>
				<figure class="testimonials__featured">
					<blockquote class="testimonials__quote testimonials__quote--featured">
						<p><?php echo esc_html( $row['testimonial']['quote'] ); ?></p>
					</blockquote>

					<figcaption class="testimonials__featured-attribution">
						<div class="testimonials__portrait testimonials__portrait--featured">
							<?php if ( $row['testimonial']['image_id'] ) : ?>
								<?php
								echo wp_get_attachment_image(
									$row['testimonial']['image_id'],
									'medium',
									false,
									array( 'class' => 'testimonials__portrait-image' )
								); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- WordPress generates escaped image markup.
								?>
							<?php else : ?>
								<span class="testimonials__portrait-fallback" aria-hidden="true"><?php echo esc_html( $row['testimonial']['initials'] ); ?></span>
							<?php endif; ?>
						</div>

						<div class="testimonials__attribution-copy">
							<strong class="testimonials__name testimonials__name--featured"><?php echo esc_html( $row['testimonial']['name'] ); ?></strong>
							<?php if ( '' !== $row['testimonial']['role'] || '' !== $row['testimonial']['organization'] ) : ?>
								<p class="testimonials__context testimonials__context--featured">
									<?php echo esc_html( $row['testimonial']['role'] ); ?><?php if ( '' !== $row['testimonial']['role'] && '' !== $row['testimonial']['organization'] ) : ?>, <?php endif; ?><?php echo esc_html( $row['testimonial']['organization'] ); ?>
								</p>
							<?php endif; ?>

							<?php if ( '' !== $row['testimonial']['detail'] ) : ?>
								<p class="testimonials__detail"><?php echo esc_html( $row['testimonial']['detail'] ); ?></p>
							<?php endif; ?>
						</div>
					</figcaption>
				</figure>
			<?php endif; ?>
		<?php endforeach; ?>
	</div>
</section>
