<?php
/**
 * Curated Content Grid block template.
 *
 * @package ACF_Module_Workbench
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$title             = trim( (string) get_field( 'title' ) );
$introduction      = trim( (string) get_field( 'introduction' ) );
$heading_level     = (string) get_field( 'heading_level' );
$selected_posts    = get_field( 'curated_posts' );
$is_editor_preview = ! empty( $is_preview );
$allowed_headings  = array( 'h2', 'h3', 'h4' );
$card_headings     = array(
	'h2' => 'h3',
	'h3' => 'h4',
	'h4' => 'h5',
);
$posts             = array();
$seen_post_ids     = array();

$heading_level = in_array( $heading_level, $allowed_headings, true ) ? $heading_level : 'h2';
$card_heading  = $card_headings[ $heading_level ];

if ( is_array( $selected_posts ) ) {
	foreach ( $selected_posts as $selected_post ) {
		$post_id = $selected_post instanceof WP_Post ? (int) $selected_post->ID : absint( $selected_post );

		if ( ! $post_id || isset( $seen_post_ids[ $post_id ] ) ) {
			continue;
		}

		$seen_post_ids[ $post_id ] = true;
		$post_object                = get_post( $post_id );

		if ( ! $post_object instanceof WP_Post || 'post' !== $post_object->post_type || 'publish' !== $post_object->post_status ) {
			continue;
		}

		$permalink  = get_permalink( $post_object );
		$post_title = trim( get_the_title( $post_object ) );

		if ( ! is_string( $permalink ) || '' === $permalink || '' === $post_title ) {
			continue;
		}

		$terms           = get_the_terms( $post_object, 'category' );
		$categories      = array();
		$image_id        = get_post_thumbnail_id( $post_object );
		$image_id        = $image_id && wp_attachment_is_image( $image_id ) ? $image_id : 0;
		$author_id       = (int) $post_object->post_author;
		$author_name     = trim( (string) get_the_author_meta( 'display_name', $author_id ) );
		$author_initials = '';
		$content_text    = trim( wp_strip_all_tags( strip_shortcodes( (string) $post_object->post_content ) ) );
		$content_tokens  = '' === $content_text ? array() : preg_split( '/\s+/u', $content_text, -1, PREG_SPLIT_NO_EMPTY );
		$content_words   = is_array( $content_tokens ) ? count( $content_tokens ) : 0;
		$reading_minutes = max( 1, (int) ceil( $content_words / 200 ) );
		$badge_palettes  = array( 'primary', 'secondary', 'accent' );
		$badge_palette   = $badge_palettes[ $author_id > 0 ? ( $author_id - 1 ) % count( $badge_palettes ) : 0 ];

		if ( '' !== $author_name ) {
			$author_parts = preg_split( '/\s+/u', $author_name, -1, PREG_SPLIT_NO_EMPTY );
			$author_parts = is_array( $author_parts ) ? $author_parts : array();
			$initial_parts = count( $author_parts ) > 1
				? array( $author_parts[0], $author_parts[ count( $author_parts ) - 1 ] )
				: $author_parts;

			foreach ( $initial_parts as $initial_part ) {
				$author_initials .= function_exists( 'mb_substr' ) ? mb_substr( $initial_part, 0, 1 ) : substr( $initial_part, 0, 1 );
			}

			$author_initials = function_exists( 'mb_strtoupper' ) ? mb_strtoupper( $author_initials ) : strtoupper( $author_initials );
		}

		if ( is_array( $terms ) ) {
			foreach ( $terms as $term ) {
				if ( $term instanceof WP_Term && '' !== trim( $term->name ) ) {
					$categories[] = $term->name;
				}
			}
		}

		$posts[] = array(
			'id'              => $post_id,
			'title'           => $post_title,
			'permalink'       => $permalink,
			'excerpt'         => trim( (string) $post_object->post_excerpt ),
			'image_id'        => $image_id,
			'categories'      => $categories,
			'date_display'    => (string) get_the_date( '', $post_object ),
			'date_machine'    => (string) get_the_date( DATE_W3C, $post_object ),
			'author_name'     => $author_name,
			'author_initials' => $author_initials,
			'badge_palette'   => $badge_palette,
			'reading_time'    => sprintf(
				/* translators: %d: Estimated reading time in minutes. */
				_n( '%d min read', '%d min read', $reading_minutes, 'acf-module-workbench' ),
				$reading_minutes
			),
		);

	}
}

if ( '' === $title || empty( $posts ) ) {
	return;
}

$heading_id         = wp_unique_id( 'curated-content-grid-heading-' );
$wrapper_attributes = get_block_wrapper_attributes(
	array(
		'class' => sprintf( 'curated-content-grid curated-content-grid--count-%d', count( $posts ) ),
	)
);
?>
<section <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?> aria-labelledby="<?php echo esc_attr( $heading_id ); ?>">
	<header class="curated-content-grid__header">
		<<?php echo esc_html( $heading_level ); ?> class="curated-content-grid__title" id="<?php echo esc_attr( $heading_id ); ?>"><?php echo esc_html( $title ); ?></<?php echo esc_html( $heading_level ); ?>>

		<?php if ( '' !== $introduction ) : ?>
			<p class="curated-content-grid__introduction"><?php echo esc_html( $introduction ); ?></p>
		<?php endif; ?>
	</header>

	<ul class="curated-content-grid__items" role="list">
		<?php foreach ( $posts as $post_item ) : ?>
			<?php
			$card_heading_id = wp_unique_id( 'curated-content-grid-card-heading-' );
			$card_classes    = 'curated-content-grid__card';

			if ( ! $post_item['image_id'] ) {
				$card_classes .= ' curated-content-grid__card--without-image';
			}

			if ( '' === $post_item['excerpt'] ) {
				$card_classes .= ' curated-content-grid__card--without-excerpt';
			}
			?>
			<li class="curated-content-grid__item">
				<article class="<?php echo esc_attr( $card_classes ); ?>" aria-labelledby="<?php echo esc_attr( $card_heading_id ); ?>">
					<div class="curated-content-grid__media">
						<?php if ( $post_item['image_id'] ) : ?>
							<?php
							echo wp_get_attachment_image(
								$post_item['image_id'],
								'large',
								false,
								array(
									'class' => 'curated-content-grid__image',
								)
							); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- WordPress generates escaped image markup.
							?>
						<?php else : ?>
							<div class="curated-content-grid__placeholder" aria-hidden="true">
								<svg class="curated-content-grid__placeholder-icon" viewBox="0 0 64 48" focusable="false">
									<rect x="5" y="5" width="54" height="38" rx="3"></rect>
									<circle cx="46" cy="16" r="5"></circle>
									<path d="M10 37 24 23l9 9 7-7 14 12"></path>
								</svg>
							</div>
						<?php endif; ?>
					</div>

					<div class="curated-content-grid__content">
						<?php if ( ! empty( $post_item['categories'] ) ) : ?>
							<ul class="curated-content-grid__categories" role="list">
								<?php foreach ( $post_item['categories'] as $category ) : ?>
									<li class="curated-content-grid__category"><?php echo esc_html( $category ); ?></li>
								<?php endforeach; ?>
							</ul>
						<?php endif; ?>

						<<?php echo esc_html( $card_heading ); ?> class="curated-content-grid__card-title" id="<?php echo esc_attr( $card_heading_id ); ?>">
							<a class="curated-content-grid__link"<?php if ( $is_editor_preview ) : ?> role="link" aria-disabled="true"<?php else : ?> href="<?php echo esc_url( $post_item['permalink'] ); ?>"<?php endif; ?>><?php echo esc_html( $post_item['title'] ); ?></a>
						</<?php echo esc_html( $card_heading ); ?>>

						<?php if ( '' !== $post_item['excerpt'] ) : ?>
							<p class="curated-content-grid__excerpt"><?php echo esc_html( $post_item['excerpt'] ); ?></p>
						<?php endif; ?>

						<footer class="curated-content-grid__byline">
							<?php if ( '' !== $post_item['author_name'] && '' !== $post_item['author_initials'] ) : ?>
								<span class="curated-content-grid__author-badge curated-content-grid__author-badge--<?php echo esc_attr( $post_item['badge_palette'] ); ?>" aria-hidden="true"><?php echo esc_html( $post_item['author_initials'] ); ?></span>
							<?php endif; ?>

							<div class="curated-content-grid__byline-copy">
								<?php if ( '' !== $post_item['author_name'] ) : ?>
									<span class="curated-content-grid__author-name"><?php echo esc_html( $post_item['author_name'] ); ?></span>
								<?php endif; ?>

								<div class="curated-content-grid__post-meta">
									<span><?php echo esc_html( $post_item['reading_time'] ); ?></span>
									<?php if ( '' !== $post_item['date_display'] && '' !== $post_item['date_machine'] ) : ?>
										<span aria-hidden="true">&bull;</span>
										<time datetime="<?php echo esc_attr( $post_item['date_machine'] ); ?>"><?php echo esc_html( $post_item['date_display'] ); ?></time>
									<?php endif; ?>
								</div>
							</div>
						</footer>
					</div>
				</article>
			</li>
		<?php endforeach; ?>
	</ul>
</section>
